#!/usr/bin/env python
###########################################################################
# obd_sensors.py
#
# Copyright 2004 Donour Sizemore (donour@uchicago.edu)
# Copyright 2009 Secons Ltd. (www.obdtester.com)
# Copyright 2021 Jure Poljsak (https://github.com/barracuda-fsh/pyobd)
# Copyright 2023 Thijs van der Woude (https://github.com/OpenCadia/OpenCadia)
#
# This file is part of OpenCadia.
#
# OpenCadia is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# OpenCadia is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR 'A' PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received 'a' copy of the GNU General Public License
# along with OpenCadia; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
###########################################################################
pcodes = {
    "P0000": "ISO/SAE Reserved",
    "P0001": "Fuel Volume Regulator Control Circuit/Open",
    "P0002": "Fuel Volume Regulator Control Circuit Range/Performance",
    "P0003": "Fuel Volume Regulator Control Circuit Low",
    "P0004": "Fuel Volume Regulator Control Circuit High",
    "P0005": "Fuel Shutoff Valve 'A' Control Circuit/Open",
    "P0006": "Fuel Shutoff Valve 'A' Control Circuit Low",
    "P0007": "Fuel Shutoff Valve 'A' Control Circuit High",
    "P0008": " Engine Positions System Performance Bank 1",
    "P0009": "Engine Position System Performance Bank 2",
    "P000A": "'A' Camshaft Position Slow Response Bank 1",
    "P000B": "'B' Camshaft Position Slow Response Bank 1",
    "P000C": "'A' Camshaft Position Slow Response Bank 2",
    "P000D": "'B' Camshaft Position Slow Response Bank 2",
    "P000E": "Fuel Volume Regulator Control Exceeded Learning Limit",
    "P000F": "Fuel System Over Pressure Relief Valve Activated",
    "P0010": "'A' Camshaft Position Actuator Circuit (Bank 1)",
    "P0011": "'A' Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
    "P0012": "'A' Camshaft Position - Timing Over-Retarded (Bank 1)",
    "P0013": "'B' Camshaft Position - Actuator Circuit (Bank 1)",
    "P0014": "'B' Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
    "P0015": "'B' Camshaft Position -Timing Over-Retarded (Bank 1)",
    "P0016": "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)",
    "P0017": "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)",
    "P0018": "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor A)",
    "P0019": "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)",
    "P001A": "'A' Camshaft Profile Control Circuit/Open Bank 1",
    "P001B": "'A' Camshaft Profile Control Circuit Low Bank 1",
    "P001C": "'A' Camshaft Profile Control Circuit High Bank 1",
    "P001D": "'A' Camshaft Profile Control Circuit/Open Bank 2",
    "P001E": "'A' Camshaft Profile Control Circuit Low Bank 2",
    "P001F": "'A' Camshaft Profile Control Circuit High Bank 2",
    "P0020": "'A' Camshaft Position Actuator Circuit (Bank 2)",
    "P0021": "'A' Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
    "P0022": "'A' Camshaft Position - Timing Over-Retarded (Bank 2)",
    "P0023": "'B' Camshaft Position - Actuator Circuit (Bank 2)",
    "P0024": "'B' Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
    "P0025": "'B' Camshaft Position - Timing Over-Retarded (Bank 2)",
    "P0026": "Intake Valve Control Solenoid Circuit Range/Performance Bank 1",
    "P0027": "Exhaust Valve Control solenoid Circuit Range/Performance Bank 1",
    "P0028": "Intake valve Control Solenoid Circuit Range/Performance Bank 2",
    "P0029": "Exhaust Valve Control Solenoid Circuit Range/Performance Bank 2",
    "P002A": "'B' Camshaft Profile Control Circuit/Open Bank 1",
    "P002B": "'B' Camshaft Profile Control Circuit Low Bank 1",
    "P002C": "'B' Camshaft Profile Control Circuit High Bank 1",
    "P002D": "'B' Camshaft Profile Control Circuit/Open Bank 2",
    "P002E": "'B' Camshaft Profile Control Circuit Low Bank 2",
    "P002F": "'B' Camshaft Profile Control Circuit High Bank 2",
    "P0030": "HO2S Heater Control Circuit (Bank 1 Sensor 1)",
    "P0031": "HO2S Heater Control Circuit Low (Bank 1 Sensor 1)",
    "P0032": "HO2S Heater Control Circuit High (Bank 1 Sensor 1)",
    "P0033": "Turbo Charger Bypass Valve Control Circuit",
    "P0034": "Turbo Charger Bypass Valve Control Circuit Low",
    "P0035": "Turbo Charger Bypass Valve Control Circuit High",
    "P0036": "HO2S Heater Control Circuit (Bank 1 Sensor 2)",
    "P0037": "HO2S Heater Control Circuit Low (Bank 1 Sensor 2)",
    "P0038": "HO2S Heater Control Circuit High (Bank 1 Sensor 2)",
    "P0039": "Turbo/Super Charger Bypass Valve Control Circuit Range/Performance",
    "P003A": "Turbocharger/Supercharger Boost Control 'A' Position Exceeded Learning Limit",
    "P003B": "Turbocharger/Supercharger Boost Control 'B' Position Exceeded Learning Limit",
    "P003C": "'A' Camshaft Profile Control Performance/Stuck Off Bank 1",
    "P003D": "'A' Camshaft Profile Control Stuck On Bank 1",
    "P003E": "'A' Camshaft Profile Control Performance/Stuck Off Bank 2",
    "P003F": "'A' Camshaft Profile Control Stuck On Bank 2",
    "P0040": "Upstream Oxygen Sensors Swapped From Bank To Bank",
    "P0041": "Downstream Oxygen Sensors Swapped From Bank To Bank",
    "P0042": "HO2S Heater Control Circuit (Bank 1 Sensor 3)",
    "P0043": "HO2S Heater Control Circuit Low (Bank 1 Sensor 3)",
    "P0044": "HO2S Heater Control Circuit High (Bank 1 Sensor 3)",
    "P0045": "Turbocharger/Supercharger Boost Control 'A' Circuit/Open",
    "P0046": "Turbocharger/Supercharger Boost Control 'A' Circuit Range/Performance",
    "P0047": "Turbocharger/Supercharger Boost Control 'A' Circuit Low",
    "P0048": "Turbocharger/Supercharger Boost Control 'A' Circuit High",
    "P0049": "Turbocharger/Supercharger Turbine Overspeed",
    "P004A": "Turbocharger/Supercharger Boost Control 'B' Circuit/Open",
    "P004B": "Turbocharger/Supercharger Boost Control 'B' Circuit Range/Performance",
    "P004C": "Turbocharger/Supercharger Boost Control 'B' Circuit Low",
    "P004D": "Turbocharger/Supercharger Boost Control 'B' Circuit High",
    "P004E": "Turbocharger/Supercharger Boost Control 'A' Circuit Intermittent/Erratic",
    "P004F": "Turbocharger/Supercharger Boost Control 'B' Circuit Intermittent/Erratic",
    "P0050": "HO2S Heater Control Circuit (Bank 2 Sensor 1)",
    "P0051": "HO2S Heater Control Circuit Low (Bank 2 Sensor 1)",
    "P0052": "HO2S Heater Control Circuit High (Bank 2 Sensor 1)",
    "P0053": "HO2S Heater Resistance (Bank 1, Sensor 1)",
    "P0054": "HO2S Heater Resistance (Bank 1, Sensor 2)",
    "P0055": "HO2S Heater Resistance (Bank 1, Sensor 3)",
    "P0056": "HO2S Heater Control Circuit (Bank 2 Sensor 2)",
    "P0057": "HO2S Heater Control Circuit Low (Bank 2 Sensor 2)",
    "P0058": "HO2S Heater Control Circuit High (Bank 2 Sensor 2)",
    "P0059": "HO2S Heater Resistance (Bank 2, Sensor 1)",
    "P005A": "'B' Camshaft Profile Control Performance/Stuck Off Bank 1",
    "P005B": "'B' Camshaft Profile Control Stuck On Bank 1",
    "P005C": "'B' Camshaft Profile Control Performance/Stuck Off Bank 2",
    "P005D": "'B' Camshaft Profile Control Stuck On Bank 2",
    "P005E": "Turbocharger/Supercharger Boost Control 'B' Supply Voltage Circuit Low",
    "P005F": "Turbocharger/Supercharger Boost Control 'B' Supply Voltage Circuit High",
    "P0060": "HO2S Heater Resistance (Bank 2, Sensor 2)",
    "P0061": "HO2S Heater Resistance (Bank 2, Sensor 3)",
    "P0062": "HO2S Heater Control Circuit (Bank 2 Sensor 3)",
    "P0063": "HO2S Heater Control Circuit Low (Bank 2 Sensor 3)",
    "P0064": "HO2S Heater Control Circuit High (Bank 2 Sensor 3)",
    "P0065": "Air Assisted Injector Control Range/Performance",
    "P0066": "Air Assisted Injector Control Circuit or Circuit Low",
    "P0067": "Air Assisted Injector Control Circuit High",
    "P0068": "MAP/MAF - Throttle Position Correlation",
    "P0069": "Manifold Absolute Pressure - Barometric Pressure Correlation",
    "P006A": "MAP - Mass or Volume Air Flow Correlation Bank 1",
    "P006B": "MAP - Exhaust Pressure Correlation",
    "P006C": "MAP - Turbocharger/Supercharger Inlet Pressure Correlation",
    "P006D": "Barometric Pressure - Turbocharger/Supercharger Inlet Pressure Correlation",
    "P006E": "Turbocharger/Supercharger Boost Control 'A' Supply Voltage Circuit Low",
    "P006F": "Turbocharger/Supercharger Boost Control 'A' Supply Voltage Circuit High",
    "P0070": "Ambient Air Temperature Sensor Circuit",
    "P0071": "Ambient Air Temperature Sensor Range/Performance",
    "P0072": "Ambient Air Temperature Sensor Circuit Low Input",
    "P0073": "Ambient Air Temperature Sensor Circuit High Input",
    "P0074": "Ambient Air Temperature Sensor Circuit Intermittent",
    "P0075": "Intake Valve Control Solenoid Circuit (Bank 1)",
    "P0076": "Intake Valve Control Solenoid Circuit Low (Bank 1)",
    "P0077": "Intake Valve Control Solenoid Circuit High (Bank 1)",
    "P0078": "Exhaust Valve Control Solenoid Circuit (Bank 1)",
    "P0079": "Exhaust Valve Control Solenoid Circuit Low (Bank 1)",
    "P007A": "Charge Air Cooler Temperature Sensor Circuit Bank 1",
    "P007B": "Charge Air Cooler Temperature Sensor Circuit Range/Performance Bank 1",
    "P007C": "Charge Air Cooler Temperature Sensor Circuit Low Bank 1",
    "P007D": "Charge Air Cooler Temperature Sensor Circuit High Bank 1",
    "P007E": "Charge Air Cooler Temperature Sensor Circuit Intermittent/Erratic Bank 1",
    "P007F": "Charge Air Cooler Temperature Sensor Bank1/Bank2 Correlation",
    "P0080": "Exhaust Valve Control Solenoid Circuit High (Bank 1)",
    "P0081": "Intake valve Control Solenoid Circuit (Bank 2)",
    "P0082": "Intake Valve Control Solenoid Circuit Low (Bank 2)",
    "P0083": "Intake Valve Control Solenoid Circuit High (Bank 2)",
    "P0084": "Exhaust Valve Control Solenoid Circuit (Bank 2)",
    "P0085": "Exhaust Valve Control Solenoid Circuit Low (Bank 2)",
    "P0086": "Exhaust Valve Control Solenoid Circuit High (Bank 2)",
    "P0087": "Fuel Rail/System Pressure - Too Low",
    "P0088": "Fuel Rail/System Pressure - Too High",
    "P0089": "Fuel Pressure Regulator 1 Performance",
    "P008A": "Low Pressure Fuel System Pressure - Too Low",
    "P008B": "Low Pressure Fuel System Pressure - Too High",
    "P008C": "Fuel Cooler Pump Control Circuit Open",
    "P008D": "Fuel Cooler Pump Control Circuit Low",
    "P008E": "Fuel Cooler Pump Control Circuit High",
    "P008F": "Engine Coolant Temperature/Fuel Temperature Correlation",
    "P0090": "Fuel Pressure Regulator 1 Control Circuit",
    "P0091": "Fuel Pressure Regulator 1 Control Circuit Low",
    "P0092": "Fuel Pressure Regulator 1 Control Circuit High",
    "P0093": "Fuel System Leak Detected - Large Leak",
    "P0094": "Fuel System Leak Detected - Small Leak",
    "P0095": "Intake Air Temperature Sensor 2 Circuit Bank 1",
    "P0096": "Intake Air Temperature Sensor 2 Circuit Range/Performance Bank 1",
    "P0097": "Intake Air Temperature Sensor 2 Circuit Low Bank 1",
    "P0098": "Intake Air Temperature Sensor 2 Circuit High Bank 1",
    "P0099": "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic Bank 1",
    "P009A": "Intake Air Temperature/Ambient Air Temperature Correlation",
    "P009B": "Fuel Pressure Relief Control Circuit/Open",
    "P009C": "Fuel Pressure Relief Control Circuit Low",
    "P009D": "Fuel Pressure Relief Control Circuit High",
    "P009E": "Fuel Pressure Relief Control Performance/Stuck Off",
    "P009F": "Fuel Pressure Relief Control Stuck On",
    "P00A0": "Charge Air Cooler Temperature Sensor Circuit Bank 2",
    "P00A1": "Charge Air Cooler Temperature Sensor Circuit Range/Performance Bank 2",
    "P00A2": "Charge Air Cooler Temperature Sensor Circuit Low Bank 2",
    "P00A3": "Charge Air Cooler Temperature Sensor Circuit High Bank 2",
    "P00A4": "Charge Air Cooler Temperature Sensor Circuit Intermittent/Erratic Bank 2",
    "P00A5": "Intake Air Temperature Sensor 2 Circuit Bank 2",
    "P00A6": "Intake Air Temperature Sensor 2 Circuit Range/Performance Bank 2",
    "P00A7": "Intake Air Temperature Sensor 2 Circuit Low Bank 2",
    "P00A8": "Intake Air Temperature Sensor 2 Circuit High Bank 2",
    "P00A9": "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic Bank 2",
    "P00AA": "Intake Air Temperature Sensor 1 Circuit Bank 2",
    "P00AB": "Intake Air Temperature Sensor 1 Circuit Range/Performance Bank 2",
    "P00AC": "Intake Air Temperature Sensor 1 Circuit Low Bank 2",
    "P00AD": "Intake Air Temperature Sensor 1 Circuit High Bank 2",
    "P00AE": "Intake Air Temperature Sensor 1 Circuit Intermittent/Erratic Bank 2",
    "P00AF": "Turbocharger/Supercharger Boost Control 'A' Module Performance",
    "P00B0": "Turbocharger/Supercharger Boost Control 'B' Module Performance",
    "P00B1": "Radiator Coolant Temperature Sensor Circuit",
    "P00B2": "Radiator Coolant Temperature Sensor Circuit Range/Performance",
    "P00B3": "Radiator Coolant Temperature Sensor Circuit Low",
    "P00B4": "Radiator Coolant Temperature Sensor Circuit High",
    "P00B5": "Radiator Coolant Temperature Sensor Circuit Intermittent/Erratic",
    "P00B6": "Radiator Coolant Temperature/Engine Coolant Temperature Correlation",
    "P00B7": "Engine Coolant Flow Low/Performance",
    "P00B8": "MAP - Mass or Volume Air Flow Correlation Bank 2",
    "P00B9": "Low Pressure Fuel System Pressure - Too Low, Low Ambient Temperature",
    "P00BA": "Low Fuel Pressure - Forced Limited Power",
    "P00BB": "Fuel Injector Insufficient Flow - Forced Limited Power",
    "P00BC": "Mass or Volume Air Flow 'A' Circuit Range/Performance - Air Flow Too Low",
    "P00BD": "Mass or Volume Air Flow 'A' Circuit Range/Performance - Air Flow Too High",
    "P00BE": "Mass or Volume Air Flow 'B' Circuit Range/Performance - Air Flow Too Low",
    "P00BF": "Mass or Volume Air Flow 'B' Circuit Range/Performance - Air Flow Too High",
    # "P00C0 - P00FF ISO/SAE Reserved",

	"P0100": "Mass or Volume Air Flow 'A' Circuit Malfunction",
    "P0101": "Mass or Volume Air Flow 'A' Circuit Range/Performance Problem",
    "P0102": "Mass or Volume Air Flow 'A' Circuit Low Input",
    "P0103": "Mass or Volume Air Flow 'A' Circuit High Input",
    "P0104": "Mass or Volume Air Flow 'A' Circuit Intermittent",
    "P0105": "Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction",
    "P0106": "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem",
    "P0107": "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input",
    "P0108": "Manifold Absolute Pressure/Barometric Pressure Circuit High Input",
    "P0109": "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent",
    "P010A": "Mass or Volume Air Flow 'B' Circuit",
    "P010B": "Mass or Volume Air Flow 'B' Circuit Range/Performance",
    "P010C": "Mass or Volume Air Flow 'B' Circuit Low",
    "P010D": "Mass or Volume Air Flow 'B' Circuit High",
    "P010E": "Mass or Volume Air Flow 'B' Circuit Intermittent/Erratic",
    "P010F": "Mass or Volume Air Flow Sensor A/B Correlation",
    "P0110": "Intake Air Temperature Circuit Malfunction Bank 1",
    "P0111": "Intake Air Temperature Circuit Range/Performance Problem Bank 1",
    "P0112": "Intake Air Temperature Circuit Low Input Bank 1",
    "P0113": "Intake Air Temperature Circuit High Input Bank 1",
    "P0114": "Intake Air Temperature Circuit Intermittent Bank 1",
    "P0115": "Engine Coolant Temperature Sensor Circuit 1 Malfunction",
    "P0116": "Engine Coolant Temperature Sensor Circuit 1 Range/Performance Problem",
    "P0117": "Engine Coolant Temperature Sensor Circuit 1 Low Input",
    "P0118": "Engine Coolant Temperature Sensor Circuit 1 High Input",
    "P0119": "Engine Coolant Temperature Sensor Circuit 1 Intermittent",
    "P011A": "Engine Coolant Temperature Sensor 1/2 Correlation",
    "P011B": "Engine Coolant Temperature/Intake Air Temperature Correlation",
    "P011C": "Charge Air Temperature/Intake Air Temperature Correlation Bank 1",
    "P011D": "Charge Air Temperature/Intake Air Temperature Correlation Bank 2",
    "P011E": "ISO/SAE Reserved",
    "P011F": "ISO/SAE Reserved",
    "P0120": "Throttle Position Sensor/Switch 'A' Circuit Malfunction",
    "P0121": "Throttle Position Sensor/Switch 'A' Circuit Range/Performance Problem",
    "P0122": "Throttle Position Sensor/Switch 'A' Circuit Low Input",
    "P0123": "Throttle Position Sensor/Switch 'A' Circuit High Input",
    "P0124": "Throttle Position Sensor/Switch 'A' Circuit Intermittent",
    "P0125": "Insufficient Coolant Temperature for Closed Loop Fuel Control",
    "P0126": "Insufficient Coolant Temperature for Stable Operation",
    "P0127": "Intake Air Temperature Too High",
    "P0128": "Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)",
    "P0129": "Barometric Pressure Too Low",
    "P012A": "Turbocharger/Supercharger Inlet Pressure Sensor Circuit (Downstream of throttle valve)",
    "P012B": "Turbocharger/Supercharger Inlet Pressure Sensor Circuit Range/Performance (Downstream of throttle valve)",
    "P012C": "Turbocharger/Supercharger Inlet Pressure Sensor Circuit Low (Downstream of throttle valve)",
    "P012D": "Turbocharger/Supercharger Inlet Pressure Sensor Circuit High (Downstream of throttle valve)",
    "P012E": "Turbocharger/Supercharger Inlet Pressure Sensor Circuit Intermittent/Erratic (Downstream of throttle valve)",
    "P012F": "ISO/SAE Reserved",
    "P0130": "02 Sensor Circuit Malfunction (Bank I Sensor 1)",
    "P0131": "02 Sensor Circuit Low Voltage (Bank I Sensor I)",
    "P0132": "02 Sensor Circuit High Voltage (Bank I Sensor 1)",
    "P0133": "02 Sensor Circuit Slow Response (Bank 1 Sensor 1)",
    "P0134": "02 Sensor Circuit No Activity Detected (Bank I Sensor 1)",
    "P0135": "02 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)",
    "P0136": "02 Sensor Circuit Malfunction (Bank I Sensor 2)",
    "P0137": "02 Sensor Circuit Low Voltage (Bank I Sensor 2)",
    "P0138": "02 Sensor Circuit High Voltage (Bank I Sensor 2)",
    "P0139": "02 Sensor Circuit Slow Response (Bank 1 Sensor 2)",
    "P013A": "O2 Sensor Slow Response - Rich to Lean (Bank 1 Sensor 2)",
    "P013B": "O2 Sensor Slow Response - Lean to Rich (Bank 1 Sensor 2)",
    "P013C": "O2 Sensor Slow Response - Rich to Lean (Bank 2 Sensor 2)",
    "P013D": "O2 Sensor Slow Response - Lean to Rich (Bank 2 Sensor 2)",
    "P013E": "O2 Sensor Delayed Response - Rich to Lean (Bank 1 Sensor 2)",
    "P013F": "O2 Sensor Delayed Response - Lean to Rich (Bank 1 Sensor 2)",
    "P0140": "02 Sensor Circuit No Activity Detected (Bank 1 Sensor 2)",
    "P0141": "02 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)",
    "P0142": "02 Sensor Circuit Malfunction (Bank 1 Sensor 3)",
    "P0143": "02 Sensor Circuit Low Voltage (Bank 1 Sensor 3)",
    "P0144": "02 Sensor Circuit High Voltage (Bank 1 Sensor 3)",
    "P0145": "02 Sensor Circuit Slow Response (Bank 1 Sensor 3)",
    "P0146": "02 Sensor Circuit No Activity Detected (Bank 1 Sensor 3)",
    "P0147": "02 Sensor Heater Circuit Malfunction (Bank 1 Sensor 3)",
    "P0148": "Fuel Delivery Error",
    "P0149": "Fuel Timing Error",
    "P014A": "O2 Sensor Delayed Response - Rich to Lean (Bank 2 Sensor 2)",
    "P014B": "O2 Sensor Delayed Response - Lean to Rich (Bank 2 Sensor 2)",
    "P014C": "O2 Sensor Slow Response - Rich to Lean (Bank 1 Sensor 1)",
    "P014D": "O2 Sensor Slow Response - Lean to Rich (Bank 1 Sensor 1)",
    "P014E": "O2 Sensor Slow Response - Rich to Lean (Bank 2 Sensor 1)",
    "P014F": "O2 Sensor Slow Response - Lean to Rich (Bank 2 Sensor 1)",
    "P0150": "02 Sensor Circuit Malfunction (Bank 2 Sensor 1)",
    "P0151": "02 Sensor Circuit Low Voltage (Bank 2 Sensor 1)",
    "P0152": "02 Sensor Circuit High Voltage (Bank 2 Sensor 1)",
    "P0153": "02 Sensor Circuit Slow Response (Bank 2 Sensor 1)",
    "P0154": "02 Sensor Circuit No Activity Detected (Bank 2 Sensor 1)",
    "P0155": "02 Sensor Heater Circuit Malfunction (Bank 2 Sensor 1)",
    "P0156": "02 Sensor Circuit Malfunction (Bank 2 Sensor 2)",
    "P0157": "02 Sensor Circuit Low Voltage (Bank 2 Sensor 2)",
    "P0158": "02 Sensor Circuit High Voltage (Bank 2 Sensor 2)",
    "P0159": "02 Sensor Circuit Slow Response (Bank 2 Sensor 2)",
    "P015A": "O2 Sensor Delayed Response - Rich to Lean (Bank 1 Sensor 1)",
    "P015B": "O2 Sensor Delayed Response - Lean to Rich (Bank 1 Sensor 1)",
    "P015C": "O2 Sensor Delayed Response - Rich to Lean (Bank 2 Sensor 1)",
    "P015D": "O2 Sensor Delayed Response - Lean to Rich (Bank 2 Sensor 1)",
    "P015E": "ISO/SAE Reserved",
    "P015F": "ISO/SAE Reserved",
    "P0160": "02 Sensor Circuit No Activity Detected (Bank 2 Sensor 2)",
    "P0161": "02 Sensor Heater Circuit Malfunction (Bank 2 Sensor 2)",
    "P0162": "02 Sensor Circuit Malfunction (Bank 2 Sensor 3)",
    "P0163": "02 Sensor Circuit Low Voltage (Bank 2 Sensor 3)",
    "P0164": "02 Sensor Circuit High Voltage (Bank 2 Sensor 3)",
    "P0165": "02 Sensor Circuit Slow Response (Bank 2 Sensor 3)",
    "P0166": "02 Sensor Circuit No Activity Detected (Bank 2 Sensor 3)",
    "P0167": "02 Sensor Heater Circuit Malfunction (Bank 2 Sensor 3)",
    "P0168": "Fuel Temperature Too High",
    "P0169": "Incorrect Fuel Composition",
    "P016A": "ISO/SAE Reserved",
    "P016B": "ISO/SAE Reserved",
    "P016C": "ISO/SAE Reserved",
    "P016D": "ISO/SAE Reserved",
    "P016E": "ISO/SAE Reserved",
    "P016F": "ISO/SAE Reserved",
    "P0170": "Fuel Trim Malfunction (Bank 1)",
    "P0171": "System too Lean (Bank 1)",
    "P0172": "System too Rich (Bank 1)",
    "P0173": "Fuel Trim Malfunction (Bank 2)",
    "P0174": "System too Lean (Bank 2)",
    "P0175": "System too Rich (Bank 2)",
    "P0176": "Fuel Composition Sensor Circuit Malfunction",
    "P0177": "Fuel Composition Sensor Circuit Range/Performance",
    "P0178": "Fuel Composition Sensor Circuit Low Input",
    "P0179": "Fuel Composition Sensor Circuit High Input",
    "P017A": "ISO/SAE Reserved",
    "P017B": "ISO/SAE Reserved",
    "P017C": "ISO/SAE Reserved",
    "P017D": "ISO/SAE Reserved",
    "P017E": "ISO/SAE Reserved",
    "P017F": "ISO/SAE Reserved",
    "P0180": "Fuel Temperature Sensor 'A' Circuit Malfunction",
    "P0181": "Fuel Temperature Sensor 'A' Circuit Range/Performance",
    "P0182": "Fuel Temperature Sensor 'A' Circuit Low Input",
    "P0183": "Fuel Temperature Sensor 'A' Circuit High Input",
    "P0184": "Fuel Temperature Sensor 'A' Circuit Intermittent",
    "P0185": "Fuel Temperature Sensor 'B' Circuit Malfunction",
    "P0186": "Fuel Temperature Sensor 'B' Circuit Range/Performance",
    "P0187": "Fuel Temperature Sensor 'B' Circuit Low Input",
    "P0188": "Fuel Temperature Sensor 'B' Circuit High Input",
    "P0189": "Fuel Temperature Sensor 'B' Circuit Intermittent",
    "P018A": "Fuel Pressure Sensor 'B' Circuit",
    "P018B": "Fuel Pressure Sensor 'B' Circuit Range/Performance",
    "P018C": "Fuel Pressure Sensor 'B' Circuit Low",
    "P018D": "Fuel Pressure Sensor 'B' Circuit High",
    "P018E": "Fuel Pressure Sensor 'B Circuit Intermittent/Erratic",
    "P018F": "Fuel System Over Pressure Relief Valve Frequent Activation",
    "P0190": "Fuel Rail Pressure Sensor 'A' Circuit",
    "P0191": "Fuel Rail Pressure Sensor 'A' Circuit Range/Performance",
    "P0192": "Fuel Rail Pressure Sensor 'A' Circuit Low Input",
    "P0193": "Fuel Rail Pressure Sensor 'A' Circuit High Input",
    "P0194": "Fuel Rail Pressure Sensor 'A' Circuit Intermittent",
    "P0195": "Engine Oil Temperature Sensor Malfunction",
    "P0196": "Engine Oil Temperature Sensor Range/Performance",
    "P0197": "Engine Oil Temperature Sensor Low",
    "P0198": "Engine Oil Temperature Sensor High",
    "P0199": "Engine Oil Temperature Sensor Intermittent",
    # "P019A - P01FF ISO/SAE Reserved",

	"P0200": "Injector Circuit Malfunction",
    "P0201": "Injector Circuit Malfunction - Cylinder 1",
    "P0202": "Injector Circuit Malfunction - Cylinder 2",
    "P0203": "Injector Circuit Malfunction - Cylinder 3",
    "P0204": "Injector Circuit Malfunction - Cylinder 4",
    "P0205": "Injector Circuit Malfunction - Cylinder 5",
    "P0206": "Injector Circuit Malfunction - Cylinder 6",
    "P0207": "Injector Circuit Malfunction - Cylinder 7",
    "P0208": "Injector Circuit Malfunction - Cylinder 8",
    "P0209": "Injector Circuit Malfunction - Cylinder 9",
    "P020A": "Cylinder 1 Injection Timing P020B Cylinder 2 Injection Timing",
    "P020C": "Cylinder 3 Injection Timing P020D Cylinder 4 Injection Timing",
    "P020E": "Cylinder 5 Injection Timing P020F Cylinder 6 Injection Timing",
    "P0210": "Injector Circuit Malfunction - Cylinder 10",
    "P0211": "Injector Circuit Malfunction - Cylinder 11",
    "P0212": "Injector Circuit Malfunction - Cylinder 12",
    "P0213": "Cold Start Injector 1 Malfunction",
    "P0214": "Cold Start Injector 2 Malfunction",
    "P0215": "Engine Shutoff Solenoid Malfunction",
    "P0216": "Injection Timing Control Circuit Malfunction",
    "P0217": "Engine Overtemp Condition",
    "P0218": "Transmission Over Temperature Condition",
    "P0219": "Engine Overspeed Condition",
    "P021A": "Cylinder 7 Injection Timing",
    "P021B": "Cylinder 8 Injection Timing",
    "P021C": "Cylinder 9 Injection Timing",
    "P021D": "Cylinder 10 Injection Timing",
    "P021E": "Cylinder 11 Injection Timing",
    "P021F": "Cylinder 12 Injection Timing",
    "P0220": "Throttle/Pedal Position Sensor/Switch'B'Circuit Malfunction",
    "P0221": "Throttle/Pedal Position Sensor/Switch'B'Circuit Range/Performance",
    "P0222": "Throttle/Pedal Position Sensor/Switch'B'Circuit Low Input",
    "P0223": "Throttle/Pedal Position Sensor/Switch'B'Circuit High Input",
    "P0224": "Throttle/Pedal Position Sensor/Switch'B'Circuit Intermittent",
    "P0225": "Throttle/Pedal Position Sensor/Switch'C'Circuit Malfunction",
    "P0226": "Throttle/Pedal Position Sensor/Switch'C'Circuit Range/Performance",
    "P0227": "Throttle/Pedal Position Sensor/Switch'C'Circuit Low Input",
    "P0228": "Throttle/Pedal Position Sensor/Switch'C'Circuit High Input",
    "P0229": "Throttle/Pedal Position Sensor/Switch'C'Circuit Intermittent",
    "P022A": "Charge Air Cooler Bypass Control 'A' Circuit Open",
    "P022B": "Charge Air Cooler Bypass Control 'A' Circuit Low",
    "P022C": "Charge Air Cooler Bypass Control 'A' Circuit High",
    "P022D": "Charge Air Cooler Bypass Control 'B' Circuit Open",
    "P022E": "Charge Air Cooler Bypass Control 'B' Circuit Low",
    "P022F": "Charge Air Cooler Bypass Control 'B' Circuit High",
    "P0230": "Fuel Pump Primary Circuit Malfunction",
    "P0231": "Fuel Pump Secondary Circuit Low",
    "P0232": "Fuel Pump Secondary Circuit High",
    "P0233": "Fuel Pump Secondary Circuit Intermittent",
    "P0234": "Engine Turbocharger/Supercharger Overboost Condition",
    "P0235": "Turbocharger Boost Sensor'A'Circuit Malfunction",
    "P0236": "Turbocharger Boost Sensor'A'Circuit Range/Performance",
    "P0237": "Turbocharger Boost Sensor'A'Circuit Low",
    "P0238": "Turbocharger Boost Sensor'A'Circuit High",
    "P0239": "Turbocharger Boost Sensor'B'Circuit Malfunction ",
    "P023A": "Charge Air Cooler Coolant Pump Control Circuit Open",
    "P023B": "Charge Air Cooler Coolant Pump Control Circuit Low",
    "P023C": "Charge Air Cooler Coolant Pump Control Circuit High",
    "P023D": "Manifold Absolute Pressure - Turbocharger/Supercharger Boost Sensor 'A' Correlation",
    "P023E": "Manifold Absolute Pressure - Turbocharger/Supercharger Boost Sensor 'B' Correlation",
    "P023F": "Fuel Pump Secondary Circuit/Open",
    "P0240": "Turbocharger Boost Sensor'B'Circuit Range/Performance",
    "P0241": "Turbocharger Boost Sensor'B'Circuit Low",
    "P0242": "Turbocharger Boost Sensor'B'Circuit High",
    "P0243": "Turbocharger Wastegate Solenoid'A'Malfunction",
    "P0244": "Turbocharger Wastegate Solenoid'A'Range/Performance",
    "P0245": "Turbocharger Wastegate Solenoid'A'Low",
    "P0246": "Turbocharger Wastegate Solenoid'A'High",
    "P0247": "Turbocharger Wastegate Solenoid'B'Malfunction",
    "P0248": "Turbocharger Wastegate Solenoid'B'Range/Performance",
    "P0249": "Turbocharger Wastegate Solenoid'B'Low",
    "P024A": "Charge Air Cooler Bypass Control 'A' Range/Performance",
    "P024B": "Charge Air Cooler Bypass Control 'A' Stuck",
    "P024C": " Charge Air Cooler Bypass Position Sensor 'A' Circuit",
    "P024D": "Charge Air Cooler Bypass Position Sensor 'A' Circuit Range/Performance",
    "P024E": "Charge Air Cooler Bypass Position Sensor 'A' Circuit Low",
    "P024F": "Charge Air Cooler Bypass Position Sensor 'A' Circuit High",
    "P0250": "Turbocharger Wastegate Solenoid'B'High",
    "P0251": "Injection Pump Fuel Metering Control'A'Malfunction (Cam/Rotor/Injector)",
    "P0252": "Injection Pump Fuel Metering Control'A'Range/Performance (Cam/Rotor/Injector)",
    "P0253": "Injection Pump Fuel Metering Control'A'Low (Cam/Rotor/Injector)",
    "P0254": "Injection Pump Fuel Metering Control'A'High (Cam/Rotor/Injector)",
    "P0255": "Injection Pump Fuel Metering Control'A'Intermittent (Cam/Rotor/Injector)",
    "P0256": "Injection Pump Fuel Metering Control'B'Malfunction (Cam/Rotor/Injector)",
    "P0257": "Injection Pump Fuel Metering Control'B'Range/Performance Injector)",
    "P0258": "Injection Pump Fuel Metering Control'B'Low (Cam/Rotor/Injector)",
    "P0259": "Injection Pump Fuel Metering Control'B'High (Cam/Rotor/Injector)",
    "P025A": "Fuel Pump Module Control Circuit/Open",
    "P025B": "Fuel Pump Module Control Circuit Range/Performance",
    "P025C": "Fuel Pump Module Control Circuit Low",
    "P025D": "Fuel Pump Module Control Circuit High",
    "P025E": "ISO/SAE Reserved",
    "P025F": "ISO/SAE Reserved",
    "P0260": "Injection Pump Fuel Metering Control 'B' Intermittent (Cam/Rotor/Injector)",
    "P0261": "Cylinder 1 Injector Circuit Low",
    "P0262": "Cylinder 1 Injector Circuit High",
    "P0263": "Cylinder 1 Contribution/Balance Fault",
    "P0264": "Cylinder 2 Injector Circuit Low",
    "P0265": "Cylinder 2 Injector Circuit High",
    "P0266": "Cylinder 2 Contribution/Balance Fault",
    "P0267": "Cylinder 3 Injector Circuit Low",
    "P0268": "Cylinder 3 Injector Circuit High",
    "P0269": "Cylinder 3 Contribution/Balance Fault",
    "P026A": "ISO/SAE Reserved",
    "P026B": "ISO/SAE Reserved",
    "P026C": "ISO/SAE Reserved",
    "P026D": "ISO/SAE Reserved",
    "P026E": "ISO/SAE Reserved",
    "P026F": "ISO/SAE Reserved",
    "P0270": "Cylinder 4 Injector Circuit Low",
    "P0271": "Cylinder 4 Injector Circuit High",
    "P0272": "Cylinder 4 Contribution/Balance Fault",
    "P0273": "Cylinder 5 Injector Circuit Low",
    "P0274": "Cylinder 5 Injector Circuit High",
    "P0275": "Cylinder 5 Contribution/Balance Fault",
    "P0276": "Cylinder 6 Injector Circuit Low",
    "P0277": "Cylinder 6 Injector Circuit High",
    "P0278": "Cylinder 6 Contribution/Balance Fault",
    "P0279": "Cylinder 7 Injector Circuit Low",
    "P027A": "ISO/SAE Reserved",
    "P027B": "ISO/SAE Reserved",
    "P027C": "ISO/SAE Reserved",
    "P027D": "ISO/SAE Reserved",
    "P027E": "ISO/SAE Reserved",
    "P027F": "ISO/SAE Reserved",
    "P0280": "Cylinder 7 Injector Circuit High",
    "P0281": "Cylinder 7 Contribution/Balance Fault",
    "P0282": "Cylinder 8 Injector Circuit Low",
    "P0283": "Cylinder 8 Injector Circuit High",
    "P0284": "Cylinder 8 Contribution/Balance Fault",
    "P0285": "Cylinder 9 Injector Circuit Low",
    "P0286": "Cylinder 9 Injector Circuit High",
    "P0287": "Cylinder 9 Contribution/Balance Fault",
    "P0288": "Cylinder 10 Injector Circuit Low",
    "P0289": "Cylinder 10 Injector Circuit High",
    "P028A": "ISO/SAE Reserved",
    "P028B": "ISO/SAE Reserved",
    "P028C": "ISO/SAE Reserved",
    "P028D": "ISO/SAE Reserved",
    "P028E": "ISO/SAE Reserved",
    "P028F": "ISO/SAE Reserved",
    "P0290": "Cylinder 10 Contribution/Balance Fault",
    "P0291": "Cylinder 11 Injector Circuit Low",
    "P0292": "Cylinder 11 Injector Circuit High",
    "P0293": "Cylinder 11 Contribution/Balance Fault",
    "P0294": "Cylinder 12 Injector Circuit Low",
    "P0295": "Cylinder 12 Injector Circuit High",
    "P0296": "Cylinder 12 Contribution/Range Fault",
    "P0297": "Vehicle Overspeed Condition",
    "P0298": "Engine Oil Over Temperature Condition",
    "P0299": "Turbocharger/Supercharger 'A' Underboost Condition",
    "P029A": "Cylinder 1 - Fuel Trim at Max Limit",
    "P029B": "Cylinder 1 - Fuel Trim at Min Limit",
    "P029C": "Cylinder 1 - Injector Restricted",
    "P029D": "Cylinder 1 - Injector Leaking",
    "P029E": "Cylinder 2 - Fuel Trim at Max Limit",
    "P029F": "Cylinder 2 - Fuel Trim at Min Limit",
    "P02A0": "Cylinder 2 - Injector Restricted",
    "P02A1": "Cylinder 2 - Injector Leaking",
    "P02A2": "Cylinder 3 - Fuel Trim at Max Limit",
    "P02A3": "Cylinder 3 - Fuel Trim at Min Limit",
    "P02A4": "Cylinder 3 - Injector Restricted",
    "P02A5": "Cylinder 3 - Injector Leaking",
    "P02A6": "Cylinder 4 - Fuel Trim at Max Limit",
    "P02A7": "Cylinder 4 - Fuel Trim at Min Limit",
    "P02A8": "Cylinder 4 - Injector Restricted",
    "P02A9": "Cylinder 4 - Injector Leaking",
    "P02AA": "Cylinder 5 - Fuel Trim at Max Limit",
    "P02AB": "Cylinder 5 - Fuel Trim at Min Limit",
    "P02AC": "Cylinder 5 - Injector Restricted",
    "P02AD": "Cylinder 5 - Injector Leaking",
    "P02AE": "Cylinder 6 - Fuel Trim at Max Limit",
    "P02AF": "Cylinder 6 - Fuel Trim at Min Limit",
    "P02B0": "Cylinder 6 - Injector Restricted",
    "P02B1": "Cylinder 6 - Injector Leaking",
    "P02B2": "Cylinder 7 - Fuel Trim at Max Limit",
    "P02B3": "Cylinder 7 - Fuel Trim at Min Limit",
    "P02B4": "Cylinder 7 - Injector Restricted",
    "P02B5": "Cylinder 7 - Injector Leaking",
    "P02B6": "Cylinder 8 - Fuel Trim at Max Limit",
    "P02B7": "Cylinder 8 - Fuel Trim at Min Limit",
    "P02B8": "Cylinder 8 - Injector Restricted",
    "P02B9": "Cylinder 8 - Injector Leaking",
    "P02BA": "Cylinder 9 - Fuel Trim at Max Limit",
    "P02BB": "Cylinder 9 - Fuel Trim at Min Limit",
    "P02BC": "Cylinder 9 - Injector Restricted",
    "P02BD": "Cylinder 9 - Injector Leaking",
    "P02BE": "Cylinder 10 - Fuel Trim at Max Limit",
    "P02BF": "Cylinder 10 - Fuel Trim at Min Limit",
    "P02C0": "Cylinder 10 - Injector Restricted",
    "P02C1": "Cylinder 10 - Injector Leaking",
    "P02C2": "Cylinder 11 - Fuel Trim at Max Limit",
    "P02C3": "Cylinder 11 - Fuel Trim at Min Limit",
    "P02C4": "Cylinder 11 - Injector Restricted",
    "P02C5": "Cylinder 11 - Injector Leaking",
    "P02C6": "Cylinder 12 - Fuel Trim at Max Limit",
    "P02C7": "Cylinder 12 - Fuel Trim at Min Limit",
    "P02C8": "Cylinder 12 - Injector Restricted",
    "P02C9": "Cylinder 12 - Injector Leaking",
    "P02CA": "Turbocharger/Supercharger 'B' Overboost Condition",
    "P02CB": "Turbocharger/Supercharger 'B' Underboost Condition",
    "P02CC": "Cylinder 1 Fuel Injector Offset Learning At Min Limit",
    "P02CD": "Cylinder 1 Fuel Injector Offset Learning At Max Limit",
    "P02CE": "Cylinder 2 Fuel Injector Offset Learning At Min Limit",
    "P02CF": "Cylinder 2 Fuel Injector Offset Learning At Max Limit",
    "P02D0": "Cylinder 3 Fuel Injector Offset Learning At Min Limit",
    "P02D1": "Cylinder 3 Fuel Injector Offset Learning At Max Limit",
    "P02D2": "Cylinder 4 Fuel Injector Offset Learning At Min Limit",
    "P02D3": "Cylinder 4 Fuel Injector Offset Learning At Max Limit",
    "P02D4": "Cylinder 5 Fuel Injector Offset Learning At Min Limit",
    "P02D5": "Cylinder 5 Fuel Injector Offset Learning At Max Limit",
    "P02D6": "Cylinder 6 Fuel Injector Offset Learning At Min Limit",
    "P02D7": "Cylinder 6 Fuel Injector Offset Learning At Max Limit",
    "P02D8": "Cylinder 7 Fuel Injector Offset Learning At Min Limit",
    "P02D9": "Cylinder 7 Fuel Injector Offset Learning At Max Limit",
    "P02DA": "Cylinder 8 Fuel Injector Offset Learning At Min Limit",
    "P02DB": "Cylinder 8 Fuel Injector Offset Learning At Max Limit",
    "P02DC": "Cylinder 9 Fuel Injector Offset Learning At Min Limit",
    "P02DD": "Cylinder 9 Fuel Injector Offset Learning At Max Limit",
    "P02DE": "Cylinder 10 Fuel Injector Offset Learning At Min Limit",
    "P02DF": "Cylinder 10 Fuel Injector Offset Learning At Max Limit",
    "P02E0": "Diesel Intake Air Flow Control Circuit/Open",
    "P02E1": "Diesel Intake Air Flow Control Performance",
    "P02E2": "Diesel Intake Air Flow Control Circuit Low",
    "P02E3": "Diesel Intake Air Flow Control Circuit High",
    "P02E4": "Diesel Intake Air Flow Control Stuck Open",
    "P02E5": "Diesel Intake Air Flow Control Stuck Closed",
    "P02E6": "Diesel Intake Air Flow Position Sensor Circuit",
    "P02E7": "Diesel Intake Air Flow Position Sensor Circuit Range/Performance",
    "P02E8": "Diesel Intake Air Flow Position Sensor Circuit Low",
    "P02E9": "Diesel Intake Air Flow Position Sensor Circuit High",
    "P02EA": "Diesel Intake Air Flow Position Sensor Circuit Intermittent/Erratic",
    "P02EB": "Diesel Intake Air Flow Control Motor Current Range/Performance",
    "P02EC": "Diesel Intake Air Flow Control System - High Air Flow Detected",
    "P02ED": "Diesel Intake Air Flow Control System - Low Air Flow Detected",
    "P02EE": "Cylinder 1 Injector Circuit Range/Performance",
    "P02EF": "Cylinder 2 Injector Circuit Range/Performance",
    "P02F0": "Cylinder 3 Injector Circuit Range/Performance",
    "P02F1": "Cylinder 4 Injector Circuit Range/Performance",
    "P02F2": "Cylinder 5 Injector Circuit Range/Performance",
    "P02F3": "Cylinder 6 Injector Circuit Range/Performance",
    "P02F4": "Cylinder 7 Injector Circuit Range/Performance",
    "P02F5": "Cylinder 8 Injector Circuit Range/Performance",
    "P02F6": "Cylinder 9 Injector Circuit Range/Performance",
    "P02F7": "Cylinder 10 Injector Circuit Range/Performance",
    "P02F8": "Cylinder 11 Injector Circuit Range/Performance",
    "P02F9": "Cylinder 12 Injector Circuit Range/Performance",
    "P02FA": "Diesel Intake Air Flow Position Sensor Minimum/Maximum Stop Performance",
    "P02FB": "ISO/SAE Reserved",
    "P02FC": "ISO/SAE Reserved",
    "P02FD": "ISO/SAE Reserved",
    "P02FE": "ISO/SAE Reserved",
    "P02FF": "ISO/SAE Reserved",

    "P0300": "Random/Multiple Cylinder Misfire Detected",
    "P0301": "Cylinder 1 Misfire Detected",
    "P0302": "Cylinder 2 Misfire Detected",
    "P0303": "Cylinder 3 Misfire Detected",
    "P0304": "Cylinder 4 Misfire Detected",
    "P0305": "Cylinder 5 Misfire Detected",
    "P0306": "Cylinder 6 Misfire Detected",
    "P0307": "Cylinder 7 Misfire Detected",
    "P0308": "Cylinder 8 Misfire Detected",
    "P0309": "Cylinder 9 Misfire Detected",
    "P030A": "ISO/SAE Reserved",
    "P030B": "ISO/SAE Reserved",
    "P030C": "ISO/SAE Reserved",
    "P030D": "ISO/SAE Reserved",
    "P030E": "ISO/SAE Reserved",
    "P030F": "ISO/SAE Reserved",
    "P0310": "Cylinder 10 Misfire Detected",
    "P0311": "Cylinder 11 Misfire Detected",
    "P0312": "Cylinder 12 Misfire Detected",
    "P0313": "Misfire Detected with Low Fuel",
    "P0314": "Single Cylinder Misfire (Cylinder not Specified)",
    "P0315": "Crankshaft Position System Variation Not Learned",
    "P0316": "Misfire Detected On Startup (First 1000 Revolutions)",
    "P0317": "Rough Road Hardware Not Present",
    "P0318": "Rough Road Sensor 'A' Signal Circuit",
    "P0319": "Rough Road Sensor 'B' Signal Circuit",
    "P031A": "ISO/SAE Reserved",
    "P031B": "ISO/SAE Reserved",
    "P031C": "ISO/SAE Reserved",
    "P031D": "ISO/SAE Reserved",
    "P031E": "ISO/SAE Reserved",
    "P031F": "ISO/SAE Reserved",
    "P0320": "Ignition/Distributor Engine Speed Input Circuit Malfunction",
    "P0321": "Ignition/Distributor Engine Speed Input Circuit Range/Performance",
    "P0322": "Ignition/Distributor Engine Speed Input Circuit No Signal",
    "P0323": "Ignition/Distributor Engine Speed Input Circuit Intermittent",
    "P0324": "Knock Control System Error",
    "P0325": "Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)",
    "P0326": "Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)",
    "P0327": "Knock Sensor 1 Circuit Low Input (Bank 1 or Single Sensor)",
    "P0328": "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)",
    "P0329": "Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)",
    "P032A": "Knock Sensor 3 Circuit Bank 1",
    "P032B": "Knock Sensor 3 Circuit Range/Performance Bank 1",
    "P032C": "Knock Sensor 3 Circuit Low Bank 1",
    "P032D": "Knock Sensor 3 Circuit High Bank 1",
    "P032E": "Knock Sensor 3 Circuit Intermittent Bank 1",
    "P032F": "ISO/SAE Reserved",
    "P0330": "Knock Sensor 2 Circuit Malfunction (Bank 2)",
    "P0331": "Knock Sensor 2 Circuit Range/Performance (Bank 2)",
    "P0332": "Knock Sensor 2 Circuit Low Input (Bank 2)",
    "P0333": "Knock Sensor 2 Circuit High Input (Bank 2)",
    "P0334": "Knock Sensor 2 Circuit Intermittent (Bank 2)",
    "P0335": "Crankshaft Position Sensor 'A' Circuit Malfunction",
    "P0336": "Crankshaft Position Sensor 'A' Circuit Range/Performance",
    "P0337": "Crankshaft Position Sensor 'A' Circuit Low Input",
    "P0338": "Crankshaft Position Sensor 'A' Circuit High Input",
    "P0339": "Crankshaft Position Sensor 'A' Circuit Intermittent",
    "P033A": "Knock Sensor 4 Circuit (Bank 2)",
    "P033B": "Knock Sensor 4 Circuit Range/Performance (Bank 2)",
    "P033C": "Knock Sensor 4 Circuit Low (Bank 2)",
    "P033D": "Knock Sensor 4 Circuit High (Bank 2)",
    "P033E": "Knock Sensor 4 Circuit Intermittent (Bank 2)",
    "P033F": "ISO/SAE Reserved",
    "P0340": "Camshaft Position Sensor Circuit Malfunction (Bank 1)",
    "P0341": "Camshaft Position Sensor Circuit Range/Performance (Bank 1)",
    "P0342": "Camshaft Position Sensor 'A' Circuit Low Input (Bank 1)",
    "P0343": "Camshaft Position Sensor 'A' Circuit High Input (Bank 1)",
    "P0344": "Camshaft Position Sensor 'A' Circuit Intermittent (Bank 1)",
    "P0345": "Camshaft Position Sensor 'A' Circuit Malfunction (Bank 2)",
    "P0346": "Camshaft Position Sensor 'A' Circuit Range/Performance (Bank 2)",
    "P0347": "Camshaft Position Sensor 'A' Circuit Low Input (Bank 2)",
    "P0348": "Camshaft Position Sensor 'A' Circuit High Input (Bank 2)",
    "P0349": "Camshaft Position Sensor 'A' Circuit Intermittent (Bank 2)",
    "P034A": "ISO/SAE Reserved",
    "P034B": "ISO/SAE Reserved",
    "P034C": "ISO/SAE Reserved",
    "P034D": "ISO/SAE Reserved",
    "P034E": "ISO/SAE Reserved",
    "P034F": "ISO/SAE Reserved",
    "P0350": "Ignition Coil Primary/Secondary Circuit Malfunction",
    "P0351": "Ignition Coil 'A' Primary/Secondary Circuit Malfunction",
    "P0352": "Ignition Coil 'B' Primary/Secondary Circuit Malfunction",
    "P0353": "Ignition Coil 'C' Primary/Secondary Circuit Malfunction",
    "P0354": "Ignition Coil 'D' Primary/Secondary Circuit Malfunction",
    "P0355": "Ignition Coil 'E' Primary/Secondary Circuit Malfunction",
    "P0356": "Ignition Coil 'F' Primary/Secondary Circuit Malfunction",
    "P0357": "Ignition Coil 'G' Primary/Secondary Circuit Malfunction",
    "P0358": "Ignition Coil 'H' Primary/Secondary Circuit Malfunction",
    "P0359": "Ignition Coil 'I' Primary/Secondary Circuit Malfunction",
    "P035A": "ISO/SAE Reserved",
    "P035B": "ISO/SAE Reserved",
    "P035C": "ISO/SAE Reserved",
    "P035D": "ISO/SAE Reserved",
    "P035D": "ISO/SAE Reserved",
    "P035E": "ISO/SAE Reserved",
    "P035F": "ISO/SAE Reserved",
    "P0360": "Ignition Coil J Primary/Secondary Circuit Malfunction",
    "P0361": "Ignition Coil K Primary/Secondary Circuit Malfunction",
    "P0362": "Ignition Coil L Primary/Secondary Circuit Malfunction",
    "P0363": "Misfire Detected - Fueling Disabled",
    "P0364": "ISO/SAE Reserved",
    "P0365": "Camshaft Position Sensor 'B' Circuit (Bank 1)",
    "P0366": "Camshaft Position Sensor 'B' Circuit Range/Performance (Bank 1)",
    "P0367": "Camshaft Position Sensor 'B' Circuit Low (Bank 1)",
    "P0368": "Camshaft Position Sensor 'B' Circuit High (Bank 1)",
    "P0369": "Camshaft Position Sensor 'B' Circuit Intermittent (Bank 1)",
    "P036A": "ISO/SAE Reserved",
    "P036B": "ISO/SAE Reserved",
    "P036C": "ISO/SAE Reserved",
    "P036D": "ISO/SAE Reserved",
    "P036E": "ISO/SAE Reserved",
    "P036F": "ISO/SAE Reserved",
    "P0370": "Timing Reference High Resolution Signal 'A' Malfunction",
    "P0371": "Timing Reference High Resolution Signal 'A' Too Many Pulses",
    "P0372": "Timing Reference High Resolution Signal 'A' Too Few Pulses",
    "P0373": "Timing Reference High Resolution Signal 'A' Intermittent/Erratic Pulses",
    "P0374": "Timing Reference High Resolution Signal 'A' No Pulses",
    "P0375": "Timing Reference High Resolution Signal 'B' Malfunction",
    "P0376": "Timing Reference High Resolution Signal 'B' Too Many Pulses",
    "P0377": "Timing Reference High Resolution Signal 'B' Too Few Pulses",
    "P0378": "Timing Reference High Resolution Signal 'B' Intermittent/Erratic Pulses",
    "P0379": "Timing Reference High Resolution Signal 'B' No Pulses",
    "P037A": "ISO/SAE Reserved",
    "P037B": "ISO/SAE Reserved",
    "P037C": "ISO/SAE Reserved",
    "P037D": "Glow Plug Sense Circuit",
    "P037E": "Glow Plug Sense Circuit Low",
    "P037F": "Glow Plug Sense Circuit High",
    "P0380": "Glow Plug/Heater Circuit 'A'",
    "P0381": "Glow Plug/Heater Indicator Circuit Malfunction",
    "P0382": "Glow Plug/Heater Circuit 'B'",
    "P0383": "Glow Plug Control Module Control Circuit Low",
    "P0384": "Glow Plug Control Module Control Circuit High",
    "P0385": "Crankshaft Position Sensor 'B' Circuit Malfunction",
    "P0386": "Crankshaft Position Sensor 'B' Circuit Range/Performance",
    "P0387": "Crankshaft Position Sensor 'B' Circuit Low Input",
    "P0388": "Crankshaft Position Sensor 'B' Circuit High Input",
    "P0389": "Crankshaft Position Sensor 'B' Circuit Intermittent",
    "P038A": "ISO/SAE Reserved",
    "P038B": "ISO/SAE Reserved",
	"P038C": "ISO/SAE Reserved",
    "P038D": "ISO/SAE Reserved",
    "P038E": "ISO/SAE Reserved",
    "P038F": "ISO/SAE Reserved",
    "P0390": "Camshaft Position Sensor 'B' Circuit (Bank 2)",
    "P0391": "Camshaft Position Sensor 'B' Circuit Range/Performance (Bank 2)",
    "P0392": "Camshaft Position Sensor 'B' Circuit Low (Bank 2)",
    "P0393": "Camshaft Position Sensor 'B' Circuit High (Bank 2)",
    "P0394": "Camshaft Position Sensor 'B' Circuit Intermittent (Bank 2)",
    # P0395 - P03FF ISO/SAE Reserved

    "U0001": "High Speed CAN Communication Bus", 
	"U0002": "High Speed CAN Communication Bus (Performance)", 
	"U0003": "High Speed CAN Communication Bus (Open)", 
	"U0004": "High Speed CAN Communication Bus (Low)", 
	"U0005": "High Speed CAN Communication Bus (High)", 
	"U0006": "High Speed CAN Communication Bus (Open)", 
	"U0007": "High Speed CAN Communication Bus (Low)", 
	"U0008": "High Speed CAN Communication Bus (High)", 
	"U0009": "High Speed CAN Communication Bus (shorted to Bus)", 
	"U0010": "Medium Speed CAN Communication Bus", 
	"U0011": "Medium Speed CAN Communication Bus (Performance)", 
	"U0012": "Medium Speed CAN Communication Bus (Open)", 
	"U0013": "Medium Speed CAN Communication Bus (Low)", 
	"U0014": "Medium Speed CAN Communication Bus (High)", 
	"U0015": "Medium Speed CAN Communication Bus (Open)", 
	"U0016": "Medium Speed CAN Communication Bus (Low)", 
	"U0017": "Medium Speed CAN Communication Bus (High)", 
	"U0018": "Medium Speed CAN Communication Bus (shorted to Bus)", 
	"U0019": "Low Speed CAN Communication Bus", 
	"U0020": "Low Speed CAN Communication Bus (Performance)", 
	"U0021": "Low Speed CAN Communication Bus (Open)", 
	"U0022": "Low Speed CAN Communication Bus (Low)", 
	"U0023": "Low Speed CAN Communication Bus (High)", 
	"U0024": "Low Speed CAN Communication Bus (Open)", 
	"U0025": "Low Speed CAN Communication Bus (Low)", 
	"U0026": "Low Speed CAN Communication Bus (High)", 
	"U0027": "Low Speed CAN Communication Bus (shorted to Bus)", 
	"U0028": "Vehicle Communication Bus 'A'", 
	"U0029": "Vehicle Communication Bus 'A' (Performance)", 
	"U0030": "Vehicle Communication Bus 'A' (Open)", 
	"U0031": "Vehicle Communication Bus 'A' (Low)", 
	"U0032": "Vehicle Communication Bus 'A' (High)", 
	"U0033": "Vehicle Communication Bus 'A' (Open)", 
	"U0034": "Vehicle Communication Bus 'A' (Low)", 
	"U0035": "Vehicle Communication Bus 'A' (High)", 
	"U0036": "Vehicle Communication Bus 'A' (shorted to Bus 'A')", 
	"U0037": "Vehicle Communication Bus 'B'", 
	"U0038": "Vehicle Communication Bus 'B' (Performance)", 
	"U0039": "Vehicle Communication Bus 'B' (Open)", 
	"U0040": "Vehicle Communication Bus 'B' (Low)", 
	"U0041": "Vehicle Communication Bus 'B' (High)", 
	"U0042": "Vehicle Communication Bus 'B' (Open)", 
	"U0043": "Vehicle Communication Bus 'B' (Low)", 
	"U0044": "Vehicle Communication Bus 'B' (High)", 
	"U0045": "Vehicle Communication Bus 'B' (shorted to Bus 'B')", 
	"U0046": "Vehicle Communication Bus 'C'", 
	"U0047": "Vehicle Communication Bus 'C' (Performance)", 
	"U0048": "Vehicle Communication Bus 'C' (Open)", 
	"U0049": "Vehicle Communication Bus 'C' (Low)", 
	"U0050": "Vehicle Communication Bus 'C' (High)", 
	"U0051": "Vehicle Communication Bus 'C' (Open)", 
	"U0052": "Vehicle Communication Bus 'C' (Low)", 
	"U0053": "Vehicle Communication Bus 'C' (High)", 
	"U0054": "Vehicle Communication Bus 'C' (shorted to Bus 'C')", 
	"U0055": "Vehicle Communication Bus 'D'", 
	"U0056": "Vehicle Communication Bus 'D' (Performance)", 
	"U0057": "Vehicle Communication Bus 'D' (Open)", 
	"U0058": "Vehicle Communication Bus 'D' (Low)", 
	"U0059": "Vehicle Communication Bus 'D' (High)", 
	"U0060": "Vehicle Communication Bus 'D' (Open)", 
	"U0061": "Vehicle Communication Bus 'D' (Low)", 
	"U0062": "Vehicle Communication Bus 'D' (High)", 
	"U0063": "Vehicle Communication Bus 'D' (shorted to Bus 'D')", 
	"U0064": "Vehicle Communication Bus 'E'", 
	"U0065": "Vehicle Communication Bus 'E' (Performance)", 
	"U0066": "Vehicle Communication Bus 'E' (Open)", 
	"U0067": "Vehicle Communication Bus 'E' (Low)", 
	"U0068": "Vehicle Communication Bus 'E' (High)", 
	"U0069": "Vehicle Communication Bus 'E' (Open)", 
	"U0070": "Vehicle Communication Bus 'E' (Low)", 
	"U0071": "Vehicle Communication Bus 'E' (High)", 
	"U0072": "Vehicle Communication Bus 'E' (shorted to Bus 'E')", 
	"U0073": "Control Module Communication Bus Off", 
	"U0074": "Reserved by J2012", 
	"U0075": "Reserved by J2012", 
	"U0076": "Reserved by J2012", 
	"U0077": "Reserved by J2012", 
	"U0078": "Reserved by J2012", 
	"U0079": "Reserved by J2012", 
	"U0080": "Reserved by J2012", 
	"U0081": "Reserved by J2012", 
	"U0082": "Reserved by J2012", 
	"U0083": "Reserved by J2012", 
	"U0084": "Reserved by J2012", 
	"U0085": "Reserved by J2012", 
	"U0086": "Reserved by J2012", 
	"U0087": "Reserved by J2012", 
	"U0088": "Reserved by J2012", 
	"U0089": "Reserved by J2012", 
	"U0090": "Reserved by J2012", 
	"U0091": "Reserved by J2012", 
	"U0092": "Reserved by J2012", 
	"U0093": "Reserved by J2012", 
	"U0094": "Reserved by J2012", 
	"U0095": "Reserved by J2012", 
	"U0096": "Reserved by J2012", 
	"U0097": "Reserved by J2012", 
	"U0098": "Reserved by J2012", 
	"U0099": "Reserved by J2012", 
	"U0100": "Lost Communication With ECM/PCM A", 
	"U0101": "Lost Communication with TCM", 
	"U0102": "Lost Communication with Transfer Case Control Module", 
	"U0103": "Lost Communication With Gear Shift Module", 
	"U0104": "Lost Communication With Cruise Control Module", 
	"U0105": "Lost Communication With Fuel Injector Control Module", 
	"U0106": "Lost Communication With Glow Plug Control Module", 
	"U0107": "Lost Communication With Throttle Actuator Control Module", 
	"U0108": "Lost Communication With Alternative Fuel Control Module", 
	"U0109": "Lost Communication With Fuel Pump Control Module", 
	"U0110": "Lost Communication With Drive Motor Control Module", 
	"U0111": "Lost Communication With Battery Energy Control Module 'A'", 
	"U0112": "Lost Communication With Battery Energy Control Module 'B'", 
	"U0113": "Lost Communication With Emissions Critical Control Information", 
	"U0114": "Lost Communication With Four-Wheel Drive Clutch Control Module", 
	"U0115": "Lost Communication With ECM/PCM B", 
	"U0116": "Reserved by J2012", 
	"U0117": "Reserved by J2012", 
	"U0118": "Reserved by J2012", 
	"U0119": "Reserved by J2012", 
	"U0120": "Reserved by J2012", 
	"U0121": "Lost Communication With Anti-Lock Brake System (ABS) Control Module", 
	"U0122": "Lost Communication With Vehicle Dynamics Control Module", 
	"U0123": "Lost Communication With Yaw Rate Sensor Module", 
	"U0124": "Lost Communication With Lateral Acceleration Sensor Module", 
	"U0125": "Lost Communication With Multi-axis Acceleration Sensor Module", 
	"U0126": "Lost Communication With Steering Angle Sensor Module", 
	"U0127": "Lost Communication With Tire Pressure Monitor Module", 
	"U0128": "Lost Communication With Park Brake Control Module", 
	"U0129": "Lost Communication With Brake System Control Module", 
	"U0130": "Lost Communication With Steering Effort Control Module", 
	"U0131": "Lost Communication With Power Steering Control Module", 
	"U0132": "Lost Communication With Ride Level Control Module", 
	"U0133": "Reserved by J2012", 
	"U0134": "Reserved by J2012", 
	"U0135": "Reserved by J2012", 
	"U0136": "Reserved by J2012", 
	"U0137": "Reserved by J2012", 
	"U0138": "Reserved by J2012", 
	"U0139": "Reserved by J2012", 
	"U0140": "Lost Communication With Body Control Module", 
	"U0141": "Lost Communication With Body Control Module 'A'", 
	"U0142": "Lost Communication With Body Control Module 'B'", 
	"U0143": "Lost Communication With Body Control Module 'C'", 
	"U0144": "Lost Communication With Body Control Module 'D'", 
	"U0145": "Lost Communication With Body Control Module 'E'", 
	"U0146": "Lost Communication With Gateway 'A'", 
	"U0147": "Lost Communication With Gateway 'B'", 
	"U0148": "Lost Communication With Gateway 'C'", 
	"U0149": "Lost Communication With Gateway 'D'", 
	"U0150": "Lost Communication With Gateway 'E'", 
	"U0151": "Lost Communication With Restraints Control Module", 
	"U0152": "Lost Communication With Side Restraints Control Module Left", 
	"U0153": "Lost Communication With Side Restraints Control Module Right", 
	"U0154": "Lost Communication With Restraints Occupant Sensing Control Module", 
	"U0155": "Lost Communication With Instrument Panel Cluster (IPC) Control Module", 
	"U0156": "Lost Communication With Information Center 'A'", 
	"U0157": "Lost Communication With Information Center 'B'", 
	"U0158": "Lost Communication With Head Up Display", 
	"U0159": "Lost Communication With Parking Assist Control Module", 
	"U0160": "Lost Communication With Audible Alert Control Module", 
	"U0161": "Lost Communication With Compass Module", 
	"U0162": "Lost Communication With Navigation Display Module", 
	"U0163": "Lost Communication With Navigation Control Module", 
	"U0164": "Lost Communication With HVAC Control Module", 
	"U0165": "Lost Communication With HVAC Control Module Rear", 
	"U0166": "Lost Communication With Auxiliary Heater Control Module", 
	"U0167": "Lost Communication With Vehicle Immobilizer Control Module", 
	"U0168": "Lost Communication With Vehicle Security Control Module", 
	"U0169": "Lost Communication With Sunroof Control Module", 
	"U0170": "Lost Communication With 'Restraints System Sensor A'", 
	"U0171": "Lost Communication With 'Restraints System Sensor B'", 
	"U0172": "Lost Communication With 'Restraints System Sensor C'", 
	"U0173": "Lost Communication With 'Restraints System Sensor D'", 
	"U0174": "Lost Communication With 'Restraints System Sensor E'", 
	"U0175": "Lost Communication With 'Restraints System Sensor F'", 
	"U0176": "Lost Communication With 'Restraints System Sensor G'", 
	"U0177": "Lost Communication With 'Restraints System Sensor H'", 
	"U0178": "Lost Communication With 'Restraints System Sensor I'", 
	"U0179": "Lost Communication With 'Restraints System Sensor J'", 
	"U0180": "Lost Communication With Automatic Lighting Control Module", 
	"U0181": "Lost Communication With Headlamp Leveling Control Module", 
	"U0182": "Lost Communication With Lighting Control Module Front", 
	"U0183": "Lost Communication With Lighting Control Module Rear", 
	"U0184": "Lost Communication With Radio", 
	"U0185": "Lost Communication With Antenna Control Module", 
	"U0186": "Lost Communication With Audio Amplifier", 
	"U0187": "Lost Communication With Digital Disc Player/Changer Module 'A'", 
	"U0188": "Lost Communication With Digital Disc Player/Changer Module 'B'", 
	"U0189": "Lost Communication With Digital Disc Player/Changer Module 'C'", 
	"U0190": "Lost Communication With Digital Disc Player/Changer Module 'D'", 
	"U0191": "Lost Communication With Television", 
	"U0192": "Lost Communication With Personal Computer", 
	"U0193": "Lost Communication With 'Digital Audio Control Module A'", 
	"U0194": "Lost Communication With 'Digital Audio Control Module B'", 
	"U0195": "Lost Communication With Subscription Entertainment Receiver Module", 
	"U0196": "Lost Communication With Rear Seat Entertainment Control Module", 
	"U0197": "Lost Communication With Telephone Control Module", 
	"U0198": "Lost Communication With Telematic Control Module", 
	"U0199": "Lost Communication With 'Door Control Module A'", 
	"U0200": "Lost Communication With 'Door Control Module B'", 
	"U0201": "Lost Communication With 'Door Control Module C'", 
	"U0202": "Lost Communication With 'Door Control Module D'", 
	"U0203": "Lost Communication With 'Door Control Module E'", 
	"U0204": "Lost Communication With 'Door Control Module F'", 
	"U0205": "Lost Communication With 'Door Control Module G'", 
	"U0206": "Lost Communication With Folding Top Control Module", 
	"U0207": "Lost Communication With Moveable Roof Control Module", 
	"U0208": "Lost Communication With 'Seat Control Module A'", 
	"U0209": "Lost Communication With 'Seat Control Module B'", 
	"U0210": "Lost Communication With 'Seat Control Module C'", 
	"U0211": "Lost Communication With 'Seat Control Module D'", 
	"U0212": "Lost Communication With Steering Column Control Module", 
	"U0213": "Lost Communication With Mirror Control Module", 
	"U0214": "Lost Communication With Remote Function Actuation", 
	"U0215": "Lost Communication With 'Door Switch A'", 
	"U0216": "Lost Communication With 'Door Switch B'", 
	"U0217": "Lost Communication With 'Door Switch C'", 
	"U0218": "Lost Communication With 'Door Switch D'", 
	"U0219": "Lost Communication With 'Door Switch E'", 
	"U0220": "Lost Communication With 'Door Switch F'", 
	"U0221": "Lost Communication With 'Door Switch G'", 
	"U0222": "Lost Communication With 'Door Window Motor A'", 
	"U0223": "Lost Communication With 'Door Window Motor B'", 
	"U0224": "Lost Communication With 'Door Window Motor C'", 
	"U0225": "Lost Communication With 'Door Window Motor D'", 
	"U0226": "Lost Communication With 'Door Window Motor E'", 
	"U0227": "Lost Communication With 'Door Window Motor F'", 
	"U0228": "Lost Communication With 'Door Window Motor G'", 
	"U0229": "Lost Communication With Heated Steering Wheel Module", 
	"U0230": "Lost Communication With Rear Gate Module", 
	"U0231": "Lost Communication With Rain Sensing Module", 
	"U0232": "Lost Communication With Side Obstacle Detection Control Module Left", 
	"U0233": "Lost Communication With Side Obstacle Detection Control Module Right", 
	"U0234": "Lost Communication With Convenience Recall Module", 
	"U0235": "Lost Communication With Cruise Control Front Distance Range Sensor", 
	"U0300": "Internal Control Module Software Incompatibility", 
	"U0301": "Software Incompatibility with ECM/PCM", 
	"U0302": "Software Incompatibility with Transmission Control Module", 
	"U0303": "Software Incompatibility with Transfer Case Control Module", 
	"U0304": "Software Incompatibility with Gear Shift Control Module", 
	"U0305": "Software Incompatibility with Cruise Control Module", 
	"U0306": "Software Incompatibility with Fuel Injector Control Module", 
	"U0307": "Software Incompatibility with Glow Plug Control Module", 
	"U0308": "Software Incompatibility with Throttle Actuator Control Module", 
	"U0309": "Software Incompatibility with Alternative Fuel Control Module", 
	"U0310": "Software Incompatibility with Fuel Pump Control Module", 
	"U0311": "Software Incompatibility with Drive Motor Control Module", 
	"U0312": "Software Incompatibility with Battery Energy Control Module A", 
	"U0313": "Software Incompatibility with Battery Energy Control Module B", 
	"U0314": "Software Incompatibility with Four-Wheel Drive Clutch Control Module", 
	"U0315": "Software Incompatibility with Anti-Lock Brake System Control Module", 
	"U0316": "Software Incompatibility with Vehicle Dynamics Control Module", 
	"U0317": "Software Incompatibility with Park Brake Control Module", 
	"U0318": "Software Incompatibility with Brake System Control Module", 
	"U0319": "Software Incompatibility with Steering Effort Control Module", 
	"U0320": "Software Incompatibility with Power Steering Control Module", 
	"U0321": "Software Incompatibility with Ride Level Control Module", 
	"U0322": "Software Incompatibility with Body Control Module", 
	"U0323": "Software Incompatibility with Instrument Panel Control Module", 
	"U0324": "Software Incompatibility with HVAC Control Module", 
	"U0325": "Software Incompatibility with Auxiliary Heater Control Module", 
	"U0326": "Software Incompatibility with Vehicle Immobilizer Control Module", 
	"U0327": "Software Incompatibility with Vehicle Security Control Module", 
	"U0328": "Software Incompatibility with Steering Angle Sensor Module", 
	"U0329": "Software Incompatibility with Steering Column Control Module", 
	"U0330": "Software Incompatibility with Tire Pressure Monitor Module", 
	"U0331": "Software Incompatibility with Body Control Module 'A'", 
	"U0400": "Invalid Data Received", 
	"U0401": "Invalid Data Received From ECM/PCM", 
	"U0402": "Invalid Data Received From Transmission Control Module", 
	"U0403": "Invalid Data Received From Transfer Case Control Module", 
	"U0404": "Invalid Data Received From Gear Shift Control Module", 
	"U0405": "Invalid Data Received From Cruise Control Module", 
	"U0406": "Invalid Data Received From Fuel Injector Control Module", 
	"U0407": "Invalid Data Received From Glow Plug Control Module", 
	"U0408": "Invalid Data Received From Throttle Actuator Control Module", 
	"U0409": "Invalid Data Received From Alternative Fuel Control Module", 
	"U0410": "Invalid Data Received From Fuel Pump Control Module", 
	"U0411": "Invalid Data Received From Drive Motor Control Module", 
	"U0412": "Invalid Data Received From Battery Energy Control Module A", 
	"U0413": "Invalid Data Received From Battery Energy Control Module B", 
	"U0414": "Invalid Data Received From Four-Wheel Drive Clutch Control Module", 
	"U0415": "Invalid Data Received From Anti-Lock Brake System Control Module", 
	"U0416": "Invalid Data Received From Vehicle Dynamics Control Module", 
	"U0417": "Invalid Data Received From Park Brake Control Module", 
	"U0418": "Invalid Data Received From Brake System Control Module", 
	"U0419": "Invalid Data Received From Steering Effort Control Module", 
	"U0420": "Invalid Data Received From Power Steering Control Module", 
	"U0421": "Invalid Data Received From Ride Level Control Module", 
	"U0422": "Invalid Data Received From Body Control Module", 
	"U0423": "Invalid Data Received From Instrument Panel Control Module", 
	"U0424": "Invalid Data Received From HVAC Control Module", 
	"U0425": "Invalid Data Received From Auxiliary Heater Control Module", 
	"U0426": "Invalid Data Received From Vehicle Immobilizer Control Module", 
	"U0427": "Invalid Data Received From Vehicle Security Control Module", 
	"U0428": "Invalid Data Received From Steering Angle Sensor Module", 
	"U0429": "Invalid Data Received From Steering Column Control Module", 
	"U0430": "Invalid Data Received From Tire Pressure Monitor Module", 
	"U0431": "Invalid Data Received From Body Control Module 'A'" 

}

pcode_classes = {
    "P00XX": "Fuel and Air Metering and Auxiliary Emission Controls",
    "P01XX": "Fuel and Air Merering",
    "P02XX": "Fuel and Air Merering",
    "P03XX": "Ignition System or Misfire",
    "P04XX": "Auxiliary Emission Controls",
    "P05XX": "Vehicle Speed, Idle Control, and Auxiliary Inputs",
    "P06XX": "Computer and Auxiliary Outputs",
    "P07XX": "Transmission",
    "P08XX": "Transmission",
    "P09XX": "Transmission",
    "P0AXX": "Hybrid Propulsion",
    "P10XX": "Manufacturer Controlled Fuel and Air Metering and Auxiliary Emission Controls",
    "P11XX": "Manufacturer Controlled Fuel and Air Merering",
    "P12XX": "Fuel and Air Merering",
    "P13XX": "Ignition System or Misfire",
    "P14XX": "Auxiliary Emission Controls",
    "P15XX": "Vehicle Speed, Idle Control, and Auxiliary Inputs",
    "P16XX": "Computer and Auxiliary Outputs",
    "P17XX": "Transmission",
    "P18XX": "Transmission",
    "P19XX": "Transmission",
    
    }

ptest= [
      "DTCs:",
      "MIL:",
      #A
      "Misfire:",
      "Fuel system:",
      "Components:",
      #B,D
      "Catalyst:",
      "Heated Catalyst:",
      "Evaporative system:",
      "Secondary Air System:",
      "A/C Refrigerant:",
      "Oxygen Sensor:",
      "Oxygen Sensor Heater:",
      "EGR SystemC7:",
]
