#!/usr/bin/env python
###########################################################################
# obd_sensors.py
#
# Copyright 2004 Donour Sizemore (donour@uchicago.edu)
# Copyright 2009 Secons Ltd. (www.obdtester.com)
# Copyright 2021 Jure Poljsak (https://github.com/barracuda-fsh/pyobd)
# Copyright 2023 Thijs van der Woude (https://github.com/OpenCadia/OpenCadia)
#
# This file is part of OpenCadia.
#
# OpenCadia is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# OpenCadia is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenCadia; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
###########################################################################
pcodes = {
    "P0000": "ISO/SAE Reserved",
    "P0001": "Fuel Volume Regulator Control Circuit/Open",
    "P0002": "Fuel Volume Regulator Control Circuit Range/Performance",
    "P0003": "Fuel Volume Regulator Control Circuit Low",
    "P0004": "Fuel Volume Regulator Control Circuit High",
    "P0005": "Fuel Shutoff Valve 'A' Control Circuit/Open",
    "P0006": "Fuel Shutoff Valve 'A' Control Circuit Low",
    "P0007": "Fuel Shutoff Valve 'A' Control Circuit High",
    "P0008": " Engine Positions System Performance Bank 1",
    "P0009": "Engine Position System Performance Bank 2",
    "P000A": "'A' Camshaft Position Slow Response Bank 1",
    "P000B": "'B' Camshaft Position Slow Response Bank 1",
    "P000C": "'A' Camshaft Position Slow Response Bank 2",
    "P000D": "'B' Camshaft Position Slow Response Bank 2",
    "P000E": "Fuel Volume Regulator Control Exceeded Learning Limit",
    "P000F": "Fuel System Over Pressure Relief Valve Activated",
    "P0010": "'A' Camshaft Position Actuator Circuit (Bank 1)",
    "P0011": "'A' Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
    "P0012": "'A' Camshaft Position - Timing Over-Retarded (Bank 1)",
    "P0013": "'B' Camshaft Position - Actuator Circuit (Bank 1)",
    "P0014": "'B' Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
    "P0015": "'B' Camshaft Position -Timing Over-Retarded (Bank 1)",
    "P0016": "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)",
    "P0017": "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)",
    "P0018": "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor A)",
    "P0019": "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)",
    "P001A": "'A' Camshaft Profile Control Circuit/Open Bank 1",
    "P001B": "'A' Camshaft Profile Control Circuit Low Bank 1",
    "P001C": "'A' Camshaft Profile Control Circuit High Bank 1",
    "P001D": "'A' Camshaft Profile Control Circuit/Open Bank 2",
    "P001E": "'A' Camshaft Profile Control Circuit Low Bank 2",
    "P001F": "'A' Camshaft Profile Control Circuit High Bank 2",
    "P0020": "'A' Camshaft Position Actuator Circuit (Bank 2)",
    "P0021": "'A' Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
    "P0022": "'A' Camshaft Position - Timing Over-Retarded (Bank 2)",
    "P0023": "'B' Camshaft Position - Actuator Circuit (Bank 2)",
    "P0024": "'B' Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
    "P0025": "'B' Camshaft Position - Timing Over-Retarded (Bank 2)",
    "P0026": "Intake Valve Control Solenoid Circuit Range/Performance Bank 1",
    "P0027": "Exhaust Valve Control solenoid Circuit Range/Performance Bank 1",
    "P0028": "Intake valve Control Solenoid Circuit Range/Performance Bank 2",
    "P0029": "Exhaust Valve Control Solenoid Circuit Range/Performance Bank 2",
    "P002A": "'B' Camshaft Profile Control Circuit/Open Bank 1",
    "P002B": "'B' Camshaft Profile Control Circuit Low Bank 1",
    "P002C": "'B' Camshaft Profile Control Circuit High Bank 1",
    "P002D": "'B' Camshaft Profile Control Circuit/Open Bank 2",
    "P002E": "'B' Camshaft Profile Control Circuit Low Bank 2",
    "P002F": "'B' Camshaft Profile Control Circuit High Bank 2",
    "P0030": "HO2S Heater Control Circuit (Bank 1 Sensor 1)",
    "P0031": "HO2S Heater Control Circuit Low (Bank 1 Sensor 1)",
    "P0032": "HO2S Heater Control Circuit High (Bank 1 Sensor 1)",
    "P0033": "Turbo Charger Bypass Valve Control Circuit",
    "P0034": "Turbo Charger Bypass Valve Control Circuit Low",
    "P0035": "Turbo Charger Bypass Valve Control Circuit High",
    "P0036": "HO2S Heater Control Circuit (Bank 1 Sensor 2)",
    "P0037": "HO2S Heater Control Circuit Low (Bank 1 Sensor 2)",
    "P0038": "HO2S Heater Control Circuit High (Bank 1 Sensor 2)",
    "P0039": "Turbo/Super Charger Bypass Valve Control Circuit Range/Performance",
    "P003A": "Turbocharger/Supercharger Boost Control 'A' Position Exceeded Learning Limit",
    "P003B": "Turbocharger/Supercharger Boost Control 'B' Position Exceeded Learning Limit",
    "P003C": "'A' Camshaft Profile Control Performance/Stuck Off Bank 1",
    "P003D": "'A' Camshaft Profile Control Stuck On Bank 1",
    "P003E": "'A' Camshaft Profile Control Performance/Stuck Off Bank 2",
    "P003F": "'A' Camshaft Profile Control Stuck On Bank 2",
    "P0040": "Upstream Oxygen Sensors Swapped From Bank To Bank",
    "P0041": "Downstream Oxygen Sensors Swapped From Bank To Bank",
    "P0042": "HO2S Heater Control Circuit (Bank 1 Sensor 3)",
    "P0043": "HO2S Heater Control Circuit Low (Bank 1 Sensor 3)",
    "P0044": "HO2S Heater Control Circuit High (Bank 1 Sensor 3)",
    "P0045": "Turbocharger/Supercharger Boost Control 'A' Circuit/Open",
    "P0046": "Turbocharger/Supercharger Boost Control 'A' Circuit Range/Performance",
    "P0047": "Turbocharger/Supercharger Boost Control 'A' Circuit Low",
    "P0048": "Turbocharger/Supercharger Boost Control 'A' Circuit High",
    "P0049": "Turbocharger/Supercharger Turbine Overspeed",
    "P004A": "Turbocharger/Supercharger Boost Control 'B' Circuit/Open",
    "P004B": "Turbocharger/Supercharger Boost Control 'B' Circuit Range/Performance",
    "P004C": "Turbocharger/Supercharger Boost Control 'B' Circuit Low",
    "P004D": "Turbocharger/Supercharger Boost Control 'B' Circuit High",
    "P004E": "Turbocharger/Supercharger Boost Control 'A' Circuit Intermittent/Erratic",
    "P004F": "Turbocharger/Supercharger Boost Control 'B' Circuit Intermittent/Erratic",
    "P0050": "HO2S Heater Control Circuit (Bank 2 Sensor 1)",
    "P0051": "HO2S Heater Control Circuit Low (Bank 2 Sensor 1)",
    "P0052": "HO2S Heater Control Circuit High (Bank 2 Sensor 1)",
    "P0053": "HO2S Heater Resistance (Bank 1, Sensor 1)",
    "P0054": "HO2S Heater Resistance (Bank 1, Sensor 2)",
    "P0055": "HO2S Heater Resistance (Bank 1, Sensor 3)",
    "P0056": "HO2S Heater Control Circuit (Bank 2 Sensor 2)",
    "P0057": "HO2S Heater Control Circuit Low (Bank 2 Sensor 2)",
    "P0058": "HO2S Heater Control Circuit High (Bank 2 Sensor 2)",
    "P0059": "HO2S Heater Resistance (Bank 2, Sensor 1)",
    "P005A": "'B' Camshaft Profile Control Performance/Stuck Off Bank 1",
    "P005B": "'B' Camshaft Profile Control Stuck On Bank 1",
    "P005C": "'B' Camshaft Profile Control Performance/Stuck Off Bank 2",
    "P005D": "'B' Camshaft Profile Control Stuck On Bank 2",
    "P005E": "Turbocharger/Supercharger Boost Control 'B' Supply Voltage Circuit Low",
    "P005F": "Turbocharger/Supercharger Boost Control 'B' Supply Voltage Circuit High",
    "P0060": "HO2S Heater Resistance (Bank 2, Sensor 2)",
    "P0061": "HO2S Heater Resistance (Bank 2, Sensor 3)",
    "P0062": "HO2S Heater Control Circuit (Bank 2 Sensor 3)",
    "P0063": "HO2S Heater Control Circuit Low (Bank 2 Sensor 3)",
    "P0064": "HO2S Heater Control Circuit High (Bank 2 Sensor 3)",
    "P0065": "Air Assisted Injector Control Range/Performance",
    "P0066": "Air Assisted Injector Control Circuit or Circuit Low",
    "P0067": "Air Assisted Injector Control Circuit High",
    "P0068": "MAP/MAF - Throttle Position Correlation",
    "P0069": "Manifold Absolute Pressure - Barometric Pressure Correlation",
    "P006A": "MAP - Mass or Volume Air Flow Correlation Bank 1",
    "P006B": "MAP - Exhaust Pressure Correlation",
    "P006C": "MAP - Turbocharger/Supercharger Inlet Pressure Correlation",
    "P006D": "Barometric Pressure - Turbocharger/Supercharger Inlet Pressure Correlation",
    "P006E": "Turbocharger/Supercharger Boost Control 'A' Supply Voltage Circuit Low",
    "P006F": "Turbocharger/Supercharger Boost Control 'A' Supply Voltage Circuit High",
    "P0070": "Ambient Air Temperature Sensor Circuit",
    "P0071": "Ambient Air Temperature Sensor Range/Performance",
    "P0072": "Ambient Air Temperature Sensor Circuit Low Input",
    "P0073": "Ambient Air Temperature Sensor Circuit High Input",
    "P0074": "Ambient Air Temperature Sensor Circuit Intermittent",
    "P0075": "Intake Valve Control Solenoid Circuit (Bank 1)",
    "P0076": "Intake Valve Control Solenoid Circuit Low (Bank 1)",
    "P0077": "Intake Valve Control Solenoid Circuit High (Bank 1)",
    "P0078": "Exhaust Valve Control Solenoid Circuit (Bank 1)",
    "P0079": "Exhaust Valve Control Solenoid Circuit Low (Bank 1)",
    "P007A": "Charge Air Cooler Temperature Sensor Circuit Bank 1",
    "P007B": "Charge Air Cooler Temperature Sensor Circuit Range/Performance Bank 1",
    "P007C": "Charge Air Cooler Temperature Sensor Circuit Low Bank 1",
    "P007D": "Charge Air Cooler Temperature Sensor Circuit High Bank 1",
    "P007E": "Charge Air Cooler Temperature Sensor Circuit Intermittent/Erratic Bank 1",
    "P007F": "Charge Air Cooler Temperature Sensor Bank1/Bank2 Correlation",
    "P0080": "Exhaust Valve Control Solenoid Circuit High (Bank 1)",
    "P0081": "Intake valve Control Solenoid Circuit (Bank 2)",
    "P0082": "Intake Valve Control Solenoid Circuit Low (Bank 2)",
    "P0083": "Intake Valve Control Solenoid Circuit High (Bank 2)",
    "P0084": "Exhaust Valve Control Solenoid Circuit (Bank 2)",
    "P0085": "Exhaust Valve Control Solenoid Circuit Low (Bank 2)",
    "P0086": "Exhaust Valve Control Solenoid Circuit High (Bank 2)",
    "P0087": "Fuel Rail/System Pressure - Too Low",
    "P0088": "Fuel Rail/System Pressure - Too High",
    "P0089": "Fuel Pressure Regulator 1 Performance",
    "P008A": "Low Pressure Fuel System Pressure - Too Low",
    "P008B": "Low Pressure Fuel System Pressure - Too High",
    "P008C": "Fuel Cooler Pump Control Circuit Open",
    "P008D": "Fuel Cooler Pump Control Circuit Low",
    "P008E": "Fuel Cooler Pump Control Circuit High",
    "P008F": "Engine Coolant Temperature/Fuel Temperature Correlation",
    "P0090": "Fuel Pressure Regulator 1 Control Circuit",
    "P0091": "Fuel Pressure Regulator 1 Control Circuit Low",
    "P0092": "Fuel Pressure Regulator 1 Control Circuit High",
    "P0093": "Fuel System Leak Detected - Large Leak",
    "P0094": "Fuel System Leak Detected - Small Leak",
    "P0095": "Intake Air Temperature Sensor 2 Circuit Bank 1",
    "P0096": "Intake Air Temperature Sensor 2 Circuit Range/Performance Bank 1",
    "P0097": "Intake Air Temperature Sensor 2 Circuit Low Bank 1",
    "P0098": "Intake Air Temperature Sensor 2 Circuit High Bank 1",
    "P0099": "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic Bank 1",
    "P009A": "Intake Air Temperature/Ambient Air Temperature Correlation",
    "P009B": "Fuel Pressure Relief Control Circuit/Open",
    "P009C": "Fuel Pressure Relief Control Circuit Low",
    "P009D": "Fuel Pressure Relief Control Circuit High",
    "P009E": "Fuel Pressure Relief Control Performance/Stuck Off",
    "P009F": "Fuel Pressure Relief Control Stuck On",
    "P00A0": "Charge Air Cooler Temperature Sensor Circuit Bank 2",
    "P00A1": "Charge Air Cooler Temperature Sensor Circuit Range/Performance Bank 2",
    "P00A2": "Charge Air Cooler Temperature Sensor Circuit Low Bank 2",
    "P00A3": "Charge Air Cooler Temperature Sensor Circuit High Bank 2",
    "P00A4": "Charge Air Cooler Temperature Sensor Circuit Intermittent/Erratic Bank 2",
    "P00A5": "Intake Air Temperature Sensor 2 Circuit Bank 2",
    "P00A6": "Intake Air Temperature Sensor 2 Circuit Range/Performance Bank 2",
    "P00A7": "Intake Air Temperature Sensor 2 Circuit Low Bank 2",
    "P00A8": "Intake Air Temperature Sensor 2 Circuit High Bank 2",
    "P00A9": "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic Bank 2",
    "P00AA": "Intake Air Temperature Sensor 1 Circuit Bank 2",
    "P00AB": "Intake Air Temperature Sensor 1 Circuit Range/Performance Bank 2",
    "P00AC": "Intake Air Temperature Sensor 1 Circuit Low Bank 2",
    "P00AD": "Intake Air Temperature Sensor 1 Circuit High Bank 2",
    "P00AE": "Intake Air Temperature Sensor 1 Circuit Intermittent/Erratic Bank 2",
    "P00AF": "Turbocharger/Supercharger Boost Control 'A' Module Performance",
    "P00B0": "Turbocharger/Supercharger Boost Control 'B' Module Performance",
    "P00B1": "Radiator Coolant Temperature Sensor Circuit",
    "P00B2": "Radiator Coolant Temperature Sensor Circuit Range/Performance",
    "P00B3": "Radiator Coolant Temperature Sensor Circuit Low",
    "P00B4": "Radiator Coolant Temperature Sensor Circuit High",
    "P00B5": "Radiator Coolant Temperature Sensor Circuit Intermittent/Erratic",
    "P00B6": "Radiator Coolant Temperature/Engine Coolant Temperature Correlation",
    "P00B7": "Engine Coolant Flow Low/Performance",
    "P00B8": "MAP - Mass or Volume Air Flow Correlation Bank 2",
    "P00B9": "Low Pressure Fuel System Pressure - Too Low, Low Ambient Temperature",
    "P00BA": "Low Fuel Pressure - Forced Limited Power",
    "P00BB": "Fuel Injector Insufficient Flow - Forced Limited Power",
    "P00BC": "Mass or Volume Air Flow 'A' Circuit Range/Performance - Air Flow Too Low",
    "P00BD": "Mass or Volume Air Flow 'A' Circuit Range/Performance - Air Flow Too High",
    "P00BE": "Mass or Volume Air Flow 'B' Circuit Range/Performance - Air Flow Too Low",
    "P00BF": "Mass or Volume Air Flow 'B' Circuit Range/Performance - Air Flow Too High",
    # "P00C0 - P00FF ISO/SAE Reserved",




	"P0001": "Fuel Volume Regulator Control Circuit / Open",
	"P0002": "Fuel Volume Regulator Control Circuit Range/Performance",
	"P0003": "Fuel Volume Regulator Control Circuit Low",
	"P0004": "Fuel Volume Regulator Control Circuit High",
	"P0005": "Fuel Shutoff Valve Control Circuit / Open",
	"P0006": "Fuel Shutoff Valve Control Circuit Low",
	"P0007": "Fuel Shutoff Valve Control Circuit High",
	"P0008": "Engine Position System Performance - Bank 1",
	"P0009": "Engine Position System Performance - Bank 1",
	"P0010": "Intake Camshaft Position Actuator Circuit / Open (Bank 1)",
	"P0011": "Intake Camshaft Position Timing - Over-Advanced (Bank 1)",
	"P0012": "Intake Camshaft Position Timing - Over-Retarded (Bank 1)",
	"P0013": "Exhaust Camshaft Position Actuator Circuit / Open (Bank 1)",
	"P0014": "Exhaust Camshaft Position Timing - Over-Advanced (Bank 1)",
	"P0015": "Exhaust Camshaft Position Timing - Over-Retarded (Bank 1)",
	"P0016": "Crankshaft Position Camshaft Position Correlation Bank 1 Sensor A",
	"P0017": "Crankshaft Position Camshaft Position Correlation Bank 1 Sensor B",
	"P0018": "Crankshaft Position Camshaft Position Correlation Bank 2 Sensor A",
	"P0019": "Crankshaft Position Camshaft Position Correlation Bank 2 Sensor B",
	"P0020": "Intake Camshaft Position Actuator Circuit / Open (Bank 2)",
	"P0021": "Intake Camshaft Position Timing - Over-Advanced (Bank 2)",
	"P0022": "Intake Camshaft Position Timing - Over-Retarded (Bank 2)",
	"P0023": "Exhaust Camshaft Position Actuator Circuit / Open (Bank 2)",
    "P0024": "Camshaft Position B - Timing Over-Advanced or System Performance (Bank 2)",
    "P0025": "Exhaust Camshaft Position Timing - Over-Retarded (Bank 2)",
    "P0026": "Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)",
    "P0027": "Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)",
    "P0028": "Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)",
    "P0029": "Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)",
    "P0030": "Heated Oxygen Sensor (H02S) Heater Control Circuit Bank 1 Sensor 1",
    "P0031": "Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 1 Sensor 1",
    "P0032": "Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 1 Sensor 1",
    "P0033": "Turbo/Super Charger Bypass Valve Control Circuit / Open",
    "P0034": "Turbo/Super Charger Bypass Valve Control Circuit Low",
    "P0035": "Turbo/Super Charger Bypass Valve Control Circuit High",
    "P0036": "Heated Oxygen Sensor (HO2S) Heater Control Circuit Bank 1 Sensor 2",
    "P0037": "Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 1 Sensor 2",
    "P0038": "Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 1 Sensor 2",
    "P0039": "Turbo/Super Charger Bypass Valve Control Circuit Range/Performance",
    "P0040": "Oxygen Sensor Signals Swapped Bank 1 Sensor 1 / Bank 2 Sensor 1",
    "P0041": "Oxygen Sensor Signals Swapped Bank 1 Sensor 2 / Bank 2 Sensor 2",
    "P0042": "HO2S Heater Control Circuit (Bank 1, Sensor 3)",
    "P0043": "HO2S Heater Control Circuit Low (Bank 1, Sensor 3)",
    "P0044": "HO2S Heater Control Circuit High (Bank 1, Sensor 3)",
    "P0045": "Turbocharger/Supercharger Boost Control 'A' Circuit / Open",
    "P0046": "Turbocharger/Supercharger Boost Control 'A' Circuit Range/Performance",
    "P0047": "Turbocharger/Supercharger Boost Control 'A' Circuit Low",
    "P0048": "Turbocharger/Supercharger Boost Control 'A' Circuit High",
    "P0049": "Turbo/Super Charger Turbine Overspeed",
    "P0050": "Heated Oxygen Sensor (HO2S) Heater Circuit Bank 2 Sensor 1",
    "P0051": "Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 2 Sensor 1",
    "P0052": "Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 2 Sensor 1",
    "P0053": "HO2S Heater Resistance Bank 1 Sensor 1 (PCM)",
    "P0054": "HO2S Heater Resistance Bank 1 Sensor 2 (PCM)",
    "P0055": "HO2S Heater Resistance Bank 1 Sensor 3 (PCM)",
    "P0056": "Heated Oxygen Sensor (HO2S) 2, Bank 2, Heater control - Circuit Malfunction",
    "P0057": "Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 2 Sensor 2",
    "P0058": "Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 2 Sensor 2",
    "P0059": "HO2S Heater Resistance (Bank 2, Sensor 1)",
    "P0060": "HO2S Heater Resistance (Bank 2, Sensor 2)",
    "P0061": "HO2S Heater Resistance (Bank 2, Sensor 3)",
    "P0062": "HO2S Heater Control Circuit (Bank 2, Sensor 3)",
    "P0063": "HO2S Heater Control Circuit Low (Bank 2, Sensor 3)",
    "P0064": "HO2S Heater Control Circuit High (Bank 2, Sensor 3)",
    "P0065": "Air Assisted Injector Control Range/Performance",
    "P0066": "Air Assisted Injector Control Circuit or Circuit Low",
    "P0067": "Air Assisted Injector Control Circuit or Circuit High",
    "P0068": "MAP / MAF - Throttle Position Correlation",
    "P0069": "MAP - Barometric Pressure Correlation",
    "P0070": "Ambient Air Temperature Sensor Circuit",
    "P0071": "Ambient Air Temperature Sensor Range/Performance",
    "P0072": "Ambient Air Temperature Sensor Circuit Low Input",
    "P0073": "Ambient Air Temperature Sensor Circuit High Input",
    "P0074": "Ambient Air Temperature Sensor Circuit Intermittent/Erratic",
    "P0075": "Intake Valve Control Circuit (Bank 2)",
    "P0076": "Intake Valve Control Circuit Low (Bank 2)",
    "P0077": "Intake Valve Control Circuit High (Bank 2)",
    "P0078": "Exhaust Valve Control Circuit (Bank 2)",
    "P0079": "Exhaust Valve Control Circuit Low (Bank 2)",
    "P0080": "Exhaust Valve Control Circuit High (Bank 2)",
    "P0081": "Intake Valve Control Circuit (Bank 2)",
    "P0082": "Intake Valve Control Circuit Low (Bank 2)",
    "P0083": "Intake Valve Control Circuit High (Bank 2)",
    "P0084": "Exhaust Valve Control Circuit (Bank 2)",
    "P0085": "Exhaust Valve Control Circuit Low (Bank 2)",
    "P0086": "Exhaust Valve Control Circuit High (Bank 2)",
    "P0087": "Fuel Rail/System Pressure - Too Low",
    "P0088": "Fuel Rail/System Pressure - Too High",
    "P0089": "Fuel Pressure Regulator Performance",
    "P0090": "Fuel Pressure Regulator Control Circuit",
    "P0091": "Fuel Pressure Regulator Control Circuit Low",
    "P0092": "Fuel Pressure Regulator Control Circuit High",
    "P0093": "Fuel System Leak Detected - Large Leak",
    "P0094": "Fuel System Leak Detected - Small Leak",
    "P0095": "Intake Air Temperature Sensor 2 Circuit",
    "P0096": "Intake Air Temperature Sensor 2 Circuit Range/Performance",
    "P0097": "Intake Air Temperature Sensor 2 Circuit Low Input",
    "P0098": "Intake Air Temperature Sensor 2 Circuit High Input",
    "P0099": "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic",

    "P00B7": "Engine Coolant Flow Low/Performance",
    "P051B": "Crankcase Pressure Sensor Circuit Range/Performance",

    "U0001": "High Speed CAN Communication Bus" , 
	"U0002": "High Speed CAN Communication Bus (Performance)" , 
	"U0003": "High Speed CAN Communication Bus (Open)" , 
	"U0004": "High Speed CAN Communication Bus (Low)" , 
	"U0005": "High Speed CAN Communication Bus (High)" , 
	"U0006": "High Speed CAN Communication Bus (Open)" , 
	"U0007": "High Speed CAN Communication Bus (Low)" , 
	"U0008": "High Speed CAN Communication Bus (High)" , 
	"U0009": "High Speed CAN Communication Bus (shorted to Bus)" , 
	"U0010": "Medium Speed CAN Communication Bus" , 
	"U0011": "Medium Speed CAN Communication Bus (Performance)" , 
	"U0012": "Medium Speed CAN Communication Bus (Open)" , 
	"U0013": "Medium Speed CAN Communication Bus (Low)" , 
	"U0014": "Medium Speed CAN Communication Bus (High)" , 
	"U0015": "Medium Speed CAN Communication Bus (Open)" , 
	"U0016": "Medium Speed CAN Communication Bus (Low)" , 
	"U0017": "Medium Speed CAN Communication Bus (High)" , 
	"U0018": "Medium Speed CAN Communication Bus (shorted to Bus)" , 
	"U0019": "Low Speed CAN Communication Bus" , 
	"U0020": "Low Speed CAN Communication Bus (Performance)" , 
	"U0021": "Low Speed CAN Communication Bus (Open)" , 
	"U0022": "Low Speed CAN Communication Bus (Low)" , 
	"U0023": "Low Speed CAN Communication Bus (High)" , 
	"U0024": "Low Speed CAN Communication Bus (Open)" , 
	"U0025": "Low Speed CAN Communication Bus (Low)" , 
	"U0026": "Low Speed CAN Communication Bus (High)" , 
	"U0027": "Low Speed CAN Communication Bus (shorted to Bus)" , 
	"U0028": "Vehicle Communication Bus A" , 
	"U0029": "Vehicle Communication Bus A (Performance)" , 
	"U0030": "Vehicle Communication Bus A (Open)" , 
	"U0031": "Vehicle Communication Bus A (Low)" , 
	"U0032": "Vehicle Communication Bus A (High)" , 
	"U0033": "Vehicle Communication Bus A (Open)" , 
	"U0034": "Vehicle Communication Bus A (Low)" , 
	"U0035": "Vehicle Communication Bus A (High)" , 
	"U0036": "Vehicle Communication Bus A (shorted to Bus A)" , 
	"U0037": "Vehicle Communication Bus B" , 
	"U0038": "Vehicle Communication Bus B (Performance)" , 
	"U0039": "Vehicle Communication Bus B (Open)" , 
	"U0040": "Vehicle Communication Bus B (Low)" , 
	"U0041": "Vehicle Communication Bus B (High)" , 
	"U0042": "Vehicle Communication Bus B (Open)" , 
	"U0043": "Vehicle Communication Bus B (Low)" , 
	"U0044": "Vehicle Communication Bus B (High)" , 
	"U0045": "Vehicle Communication Bus B (shorted to Bus B)" , 
	"U0046": "Vehicle Communication Bus C" , 
	"U0047": "Vehicle Communication Bus C (Performance)" , 
	"U0048": "Vehicle Communication Bus C (Open)" , 
	"U0049": "Vehicle Communication Bus C (Low)" , 
	"U0050": "Vehicle Communication Bus C (High)" , 
	"U0051": "Vehicle Communication Bus C (Open)" , 
	"U0052": "Vehicle Communication Bus C (Low)" , 
	"U0053": "Vehicle Communication Bus C (High)" , 
	"U0054": "Vehicle Communication Bus C (shorted to Bus C)" , 
	"U0055": "Vehicle Communication Bus D" , 
	"U0056": "Vehicle Communication Bus D (Performance)" , 
	"U0057": "Vehicle Communication Bus D (Open)" , 
	"U0058": "Vehicle Communication Bus D (Low)" , 
	"U0059": "Vehicle Communication Bus D (High)" , 
	"U0060": "Vehicle Communication Bus D (Open)" , 
	"U0061": "Vehicle Communication Bus D (Low)" , 
	"U0062": "Vehicle Communication Bus D (High)" , 
	"U0063": "Vehicle Communication Bus D (shorted to Bus D)" , 
	"U0064": "Vehicle Communication Bus E" , 
	"U0065": "Vehicle Communication Bus E (Performance)" , 
	"U0066": "Vehicle Communication Bus E (Open)" , 
	"U0067": "Vehicle Communication Bus E (Low)" , 
	"U0068": "Vehicle Communication Bus E (High)" , 
	"U0069": "Vehicle Communication Bus E (Open)" , 
	"U0070": "Vehicle Communication Bus E (Low)" , 
	"U0071": "Vehicle Communication Bus E (High)" , 
	"U0072": "Vehicle Communication Bus E (shorted to Bus E)" , 
	"U0073": "Control Module Communication Bus Off" , 
	"U0074": "Reserved by J2012" , 
	"U0075": "Reserved by J2012" , 
	"U0076": "Reserved by J2012" , 
	"U0077": "Reserved by J2012" , 
	"U0078": "Reserved by J2012" , 
	"U0079": "Reserved by J2012" , 
	"U0080": "Reserved by J2012" , 
	"U0081": "Reserved by J2012" , 
	"U0082": "Reserved by J2012" , 
	"U0083": "Reserved by J2012" , 
	"U0084": "Reserved by J2012" , 
	"U0085": "Reserved by J2012" , 
	"U0086": "Reserved by J2012" , 
	"U0087": "Reserved by J2012" , 
	"U0088": "Reserved by J2012" , 
	"U0089": "Reserved by J2012" , 
	"U0090": "Reserved by J2012" , 
	"U0091": "Reserved by J2012" , 
	"U0092": "Reserved by J2012" , 
	"U0093": "Reserved by J2012" , 
	"U0094": "Reserved by J2012" , 
	"U0095": "Reserved by J2012" , 
	"U0096": "Reserved by J2012" , 
	"U0097": "Reserved by J2012" , 
	"U0098": "Reserved by J2012" , 
	"U0099": "Reserved by J2012" , 
	"U0100": "Lost Communication With ECM/PCM A" , 
	"U0101": "Lost Communication with TCM" , 
	"U0102": "Lost Communication with Transfer Case Control Module" , 
	"U0103": "Lost Communication With Gear Shift Module" , 
	"U0104": "Lost Communication With Cruise Control Module" , 
	"U0105": "Lost Communication With Fuel Injector Control Module" , 
	"U0106": "Lost Communication With Glow Plug Control Module" , 
	"U0107": "Lost Communication With Throttle Actuator Control Module" , 
	"U0108": "Lost Communication With Alternative Fuel Control Module" , 
	"U0109": "Lost Communication With Fuel Pump Control Module" , 
	"U0110": "Lost Communication With Drive Motor Control Module" , 
	"U0111": "Lost Communication With Battery Energy Control Module 'A'" , 
	"U0112": "Lost Communication With Battery Energy Control Module 'B'" , 
	"U0113": "Lost Communication With Emissions Critical Control Information" , 
	"U0114": "Lost Communication With Four-Wheel Drive Clutch Control Module" , 
	"U0115": "Lost Communication With ECM/PCM B" , 
	"U0116": "Reserved by J2012" , 
	"U0117": "Reserved by J2012" , 
	"U0118": "Reserved by J2012" , 
	"U0119": "Reserved by J2012" , 
	"U0120": "Reserved by J2012" , 
	"U0121": "Lost Communication With Anti-Lock Brake System (ABS) Control Module" , 
	"U0122": "Lost Communication With Vehicle Dynamics Control Module" , 
	"U0123": "Lost Communication With Yaw Rate Sensor Module" , 
	"U0124": "Lost Communication With Lateral Acceleration Sensor Module" , 
	"U0125": "Lost Communication With Multi-axis Acceleration Sensor Module" , 
	"U0126": "Lost Communication With Steering Angle Sensor Module" , 
	"U0127": "Lost Communication With Tire Pressure Monitor Module" , 
	"U0128": "Lost Communication With Park Brake Control Module" , 
	"U0129": "Lost Communication With Brake System Control Module" , 
	"U0130": "Lost Communication With Steering Effort Control Module" , 
	"U0131": "Lost Communication With Power Steering Control Module" , 
	"U0132": "Lost Communication With Ride Level Control Module" , 
	"U0133": "Reserved by J2012" , 
	"U0134": "Reserved by J2012" , 
	"U0135": "Reserved by J2012" , 
	"U0136": "Reserved by J2012" , 
	"U0137": "Reserved by J2012" , 
	"U0138": "Reserved by J2012" , 
	"U0139": "Reserved by J2012" , 
	"U0140": "Lost Communication With Body Control Module" , 
	"U0141": "Lost Communication With Body Control Module 'A'" , 
	"U0142": "Lost Communication With Body Control Module 'B'" , 
	"U0143": "Lost Communication With Body Control Module 'C'" , 
	"U0144": "Lost Communication With Body Control Module 'D'" , 
	"U0145": "Lost Communication With Body Control Module 'E'" , 
	"U0146": "Lost Communication With Gateway 'A'" , 
	"U0147": "Lost Communication With Gateway 'B'" , 
	"U0148": "Lost Communication With Gateway 'C'" , 
	"U0149": "Lost Communication With Gateway 'D'" , 
	"U0150": "Lost Communication With Gateway 'E'" , 
	"U0151": "Lost Communication With Restraints Control Module" , 
	"U0152": "Lost Communication With Side Restraints Control Module Left" , 
	"U0153": "Lost Communication With Side Restraints Control Module Right" , 
	"U0154": "Lost Communication With Restraints Occupant Sensing Control Module" , 
	"U0155": "Lost Communication With Instrument Panel Cluster (IPC) Control Module" , 
	"U0156": "Lost Communication With Information Center 'A'" , 
	"U0157": "Lost Communication With Information Center 'B'" , 
	"U0158": "Lost Communication With Head Up Display" , 
	"U0159": "Lost Communication With Parking Assist Control Module" , 
	"U0160": "Lost Communication With Audible Alert Control Module" , 
	"U0161": "Lost Communication With Compass Module" , 
	"U0162": "Lost Communication With Navigation Display Module" , 
	"U0163": "Lost Communication With Navigation Control Module" , 
	"U0164": "Lost Communication With HVAC Control Module" , 
	"U0165": "Lost Communication With HVAC Control Module Rear" , 
	"U0166": "Lost Communication With Auxiliary Heater Control Module" , 
	"U0167": "Lost Communication With Vehicle Immobilizer Control Module" , 
	"U0168": "Lost Communication With Vehicle Security Control Module" , 
	"U0169": "Lost Communication With Sunroof Control Module" , 
	"U0170": "Lost Communication With 'Restraints System Sensor A'" , 
	"U0171": "Lost Communication With 'Restraints System Sensor B'" , 
	"U0172": "Lost Communication With 'Restraints System Sensor C'" , 
	"U0173": "Lost Communication With 'Restraints System Sensor D'" , 
	"U0174": "Lost Communication With 'Restraints System Sensor E'" , 
	"U0175": "Lost Communication With 'Restraints System Sensor F'" , 
	"U0176": "Lost Communication With 'Restraints System Sensor G'" , 
	"U0177": "Lost Communication With 'Restraints System Sensor H'" , 
	"U0178": "Lost Communication With 'Restraints System Sensor I'" , 
	"U0179": "Lost Communication With 'Restraints System Sensor J'" , 
	"U0180": "Lost Communication With Automatic Lighting Control Module" , 
	"U0181": "Lost Communication With Headlamp Leveling Control Module" , 
	"U0182": "Lost Communication With Lighting Control Module Front" , 
	"U0183": "Lost Communication With Lighting Control Module Rear" , 
	"U0184": "Lost Communication With Radio" , 
	"U0185": "Lost Communication With Antenna Control Module" , 
	"U0186": "Lost Communication With Audio Amplifier" , 
	"U0187": "Lost Communication With Digital Disc Player/Changer Module 'A'" , 
	"U0188": "Lost Communication With Digital Disc Player/Changer Module 'B'" , 
	"U0189": "Lost Communication With Digital Disc Player/Changer Module 'C'" , 
	"U0190": "Lost Communication With Digital Disc Player/Changer Module 'D'" , 
	"U0191": "Lost Communication With Television" , 
	"U0192": "Lost Communication With Personal Computer" , 
	"U0193": "Lost Communication With 'Digital Audio Control Module A'" , 
	"U0194": "Lost Communication With 'Digital Audio Control Module B'" , 
	"U0195": "Lost Communication With Subscription Entertainment Receiver Module" , 
	"U0196": "Lost Communication With Rear Seat Entertainment Control Module" , 
	"U0197": "Lost Communication With Telephone Control Module" , 
	"U0198": "Lost Communication With Telematic Control Module" , 
	"U0199": "Lost Communication With 'Door Control Module A'" , 
	"U0200": "Lost Communication With 'Door Control Module B'" , 
	"U0201": "Lost Communication With 'Door Control Module C'" , 
	"U0202": "Lost Communication With 'Door Control Module D'" , 
	"U0203": "Lost Communication With 'Door Control Module E'" , 
	"U0204": "Lost Communication With 'Door Control Module F'" , 
	"U0205": "Lost Communication With 'Door Control Module G'" , 
	"U0206": "Lost Communication With Folding Top Control Module" , 
	"U0207": "Lost Communication With Moveable Roof Control Module" , 
	"U0208": "Lost Communication With 'Seat Control Module A'" , 
	"U0209": "Lost Communication With 'Seat Control Module B'" , 
	"U0210": "Lost Communication With 'Seat Control Module C'" , 
	"U0211": "Lost Communication With 'Seat Control Module D'" , 
	"U0212": "Lost Communication With Steering Column Control Module" , 
	"U0213": "Lost Communication With Mirror Control Module" , 
	"U0214": "Lost Communication With Remote Function Actuation" , 
	"U0215": "Lost Communication With 'Door Switch A'" , 
	"U0216": "Lost Communication With 'Door Switch B'" , 
	"U0217": "Lost Communication With 'Door Switch C'" , 
	"U0218": "Lost Communication With 'Door Switch D'" , 
	"U0219": "Lost Communication With 'Door Switch E'" , 
	"U0220": "Lost Communication With 'Door Switch F'" , 
	"U0221": "Lost Communication With 'Door Switch G'" , 
	"U0222": "Lost Communication With 'Door Window Motor A'" , 
	"U0223": "Lost Communication With 'Door Window Motor B'" , 
	"U0224": "Lost Communication With 'Door Window Motor C'" , 
	"U0225": "Lost Communication With 'Door Window Motor D'" , 
	"U0226": "Lost Communication With 'Door Window Motor E'" , 
	"U0227": "Lost Communication With 'Door Window Motor F'" , 
	"U0228": "Lost Communication With 'Door Window Motor G'" , 
	"U0229": "Lost Communication With Heated Steering Wheel Module" , 
	"U0230": "Lost Communication With Rear Gate Module" , 
	"U0231": "Lost Communication With Rain Sensing Module" , 
	"U0232": "Lost Communication With Side Obstacle Detection Control Module Left" , 
	"U0233": "Lost Communication With Side Obstacle Detection Control Module Right" , 
	"U0234": "Lost Communication With Convenience Recall Module" , 
	"U0235": "Lost Communication With Cruise Control Front Distance Range Sensor" , 
	"U0300": "Internal Control Module Software Incompatibility" , 
	"U0301": "Software Incompatibility with ECM/PCM" , 
	"U0302": "Software Incompatibility with Transmission Control Module" , 
	"U0303": "Software Incompatibility with Transfer Case Control Module" , 
	"U0304": "Software Incompatibility with Gear Shift Control Module" , 
	"U0305": "Software Incompatibility with Cruise Control Module" , 
	"U0306": "Software Incompatibility with Fuel Injector Control Module" , 
	"U0307": "Software Incompatibility with Glow Plug Control Module" , 
	"U0308": "Software Incompatibility with Throttle Actuator Control Module" , 
	"U0309": "Software Incompatibility with Alternative Fuel Control Module" , 
	"U0310": "Software Incompatibility with Fuel Pump Control Module" , 
	"U0311": "Software Incompatibility with Drive Motor Control Module" , 
	"U0312": "Software Incompatibility with Battery Energy Control Module A" , 
	"U0313": "Software Incompatibility with Battery Energy Control Module B" , 
	"U0314": "Software Incompatibility with Four-Wheel Drive Clutch Control Module" , 
	"U0315": "Software Incompatibility with Anti-Lock Brake System Control Module" , 
	"U0316": "Software Incompatibility with Vehicle Dynamics Control Module" , 
	"U0317": "Software Incompatibility with Park Brake Control Module" , 
	"U0318": "Software Incompatibility with Brake System Control Module" , 
	"U0319": "Software Incompatibility with Steering Effort Control Module" , 
	"U0320": "Software Incompatibility with Power Steering Control Module" , 
	"U0321": "Software Incompatibility with Ride Level Control Module" , 
	"U0322": "Software Incompatibility with Body Control Module" , 
	"U0323": "Software Incompatibility with Instrument Panel Control Module" , 
	"U0324": "Software Incompatibility with HVAC Control Module" , 
	"U0325": "Software Incompatibility with Auxiliary Heater Control Module" , 
	"U0326": "Software Incompatibility with Vehicle Immobilizer Control Module" , 
	"U0327": "Software Incompatibility with Vehicle Security Control Module" , 
	"U0328": "Software Incompatibility with Steering Angle Sensor Module" , 
	"U0329": "Software Incompatibility with Steering Column Control Module" , 
	"U0330": "Software Incompatibility with Tire Pressure Monitor Module" , 
	"U0331": "Software Incompatibility with Body Control Module 'A'" , 
	"U0400": "Invalid Data Received" , 
	"U0401": "Invalid Data Received From ECM/PCM" , 
	"U0402": "Invalid Data Received From Transmission Control Module" , 
	"U0403": "Invalid Data Received From Transfer Case Control Module" , 
	"U0404": "Invalid Data Received From Gear Shift Control Module" , 
	"U0405": "Invalid Data Received From Cruise Control Module" , 
	"U0406": "Invalid Data Received From Fuel Injector Control Module" , 
	"U0407": "Invalid Data Received From Glow Plug Control Module" , 
	"U0408": "Invalid Data Received From Throttle Actuator Control Module" , 
	"U0409": "Invalid Data Received From Alternative Fuel Control Module" , 
	"U0410": "Invalid Data Received From Fuel Pump Control Module" , 
	"U0411": "Invalid Data Received From Drive Motor Control Module" , 
	"U0412": "Invalid Data Received From Battery Energy Control Module A" , 
	"U0413": "Invalid Data Received From Battery Energy Control Module B" , 
	"U0414": "Invalid Data Received From Four-Wheel Drive Clutch Control Module" , 
	"U0415": "Invalid Data Received From Anti-Lock Brake System Control Module" , 
	"U0416": "Invalid Data Received From Vehicle Dynamics Control Module" , 
	"U0417": "Invalid Data Received From Park Brake Control Module" , 
	"U0418": "Invalid Data Received From Brake System Control Module" , 
	"U0419": "Invalid Data Received From Steering Effort Control Module" , 
	"U0420": "Invalid Data Received From Power Steering Control Module" , 
	"U0421": "Invalid Data Received From Ride Level Control Module" , 
	"U0422": "Invalid Data Received From Body Control Module" , 
	"U0423": "Invalid Data Received From Instrument Panel Control Module" , 
	"U0424": "Invalid Data Received From HVAC Control Module" , 
	"U0425": "Invalid Data Received From Auxiliary Heater Control Module" , 
	"U0426": "Invalid Data Received From Vehicle Immobilizer Control Module" , 
	"U0427": "Invalid Data Received From Vehicle Security Control Module" , 
	"U0428": "Invalid Data Received From Steering Angle Sensor Module" , 
	"U0429": "Invalid Data Received From Steering Column Control Module" , 
	"U0430": "Invalid Data Received From Tire Pressure Monitor Module" , 
	"U0431": "Invalid Data Received From Body Control Module 'A'" 

}

pcode_classes = {
    "P00XX": "Fuel and Air Metering and Auxiliary Emission Controls",
    "P01XX": "Fuel and Air Merering",
    "P02XX": "Fuel and Air Merering",
    "P03XX": "Ignition System or Misfire",
    "P04XX": "Auxiliary Emission Controls",
    "P05XX": "Vehicle Speed, Idle Control, and Auxiliary Inputs",
    "P06XX": "Computer and Auxiliary Outputs",
    "P07XX": "Transmission",
    "P08XX": "Transmission",
    "P09XX": "Transmission",
    "P0AXX": "Hybrid Propulsion",
    "P10XX": "Manufacturer Controlled Fuel and Air Metering and Auxiliary Emission Controls",
    "P11XX": "Manufacturer Controlled Fuel and Air Merering",
    "P12XX": "Fuel and Air Merering",
    "P13XX": "Ignition System or Misfire",
    "P14XX": "Auxiliary Emission Controls",
    "P15XX": "Vehicle Speed, Idle Control, and Auxiliary Inputs",
    "P16XX": "Computer and Auxiliary Outputs",
    "P17XX": "Transmission",
    "P18XX": "Transmission",
    "P19XX": "Transmission",
    
    }

ptest= [
      "DTCs:",
      "MIL:",
      #A
      "Misfire:",
      "Fuel system:",
      "Components:",
      #B,D
      "Catalyst:",
      "Heated Catalyst:",
      "Evaporative system:",
      "Secondary Air System:",
      "A/C Refrigerant:" ,
      "Oxygen Sensor:",
      "Oxygen Sensor Heater:",
      "EGR SystemC7:" ,
]
